-- 12 · Journey content for LT Bachelor, imported from the Excel source of truth.
--
-- Generated by scripts/import-journey.mjs — do not hand-edit. Re-run the script
-- after the Excel changes and apply the new file.
--
-- Source: /home/szei/Documents/Important-AW/Bachelor-Journey-stages-lt.xlsx
-- Stages: 3 · Steps: 16 · Plans: self_service, full_service
-- Skipped, not specified in the Excel yet: e signature
--
-- Idempotent: stages and steps are matched by title, so re-running updates the
-- existing rows and never deletes a step that student progress points at.

do $$
declare
  v_plan   text;
  v_stage  uuid;
  v_step   uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop


  /* ── Stage 1 : Pre-Application ── */
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'Pre-Application' limit 1;

  if v_stage is null then
    insert into public.journey_stages (country, plan, sort_order, title, description, icon, tone, status, rules)
    values ('LT', v_plan, 0, 'Pre-Application', '', 'landmark', 'purple', 'published', '{"degree":"Bachelor","source":"xlsx","excelStage":"Stage 1 : Pre-Application"}'::jsonb)
    returning id into v_stage;
  else
    update public.journey_stages
       set sort_order = 0, icon = 'landmark', tone = 'purple',
           status = 'published', rules = '{"degree":"Bachelor","source":"xlsx","excelStage":"Stage 1 : Pre-Application"}'::jsonb
     where id = v_stage;
  end if;


  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Explore Your Program' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 0, 'Explore Your Program', 'Review your chosen program carefully to understand its requirements, curriculum, tuition, duration, and career opportunities before you apply.', 'published', true, '{"documents":[],"allowSkip":false,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 0, description = 'Review your chosen program carefully to understand its requirements, curriculum, tuition, duration, and career opportunities before you apply.', status = 'published',
           required = true, rules = '{"documents":[],"allowSkip":false,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'program', true, '', '', '{"field":"url","source":"xlsx"}'::jsonb, 'student');
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 1, 'paragraph', true, '', 'link of the program page', '{"source":"xlsx"}'::jsonb, 'student');

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Passport' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 1, 'Passport', 'Ensure you have a valid passport with sufficient validity before starting your university application', 'published', true, '{"documents":[{"key":"passport","name":"Passport","description":"Ensure you have a valid passport with sufficient validity before starting your university application","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 1, description = 'Ensure you have a valid passport with sufficient validity before starting your university application', status = 'published',
           required = true, rules = '{"documents":[{"key":"passport","name":"Passport","description":"Ensure you have a valid passport with sufficient validity before starting your university application","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'paragraph', true, '', 'Watch the tutorial video, then apply for your passport on the official website.Tutorial:', '{"source":"xlsx"}'::jsonb, 'student');
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 1, 'video', true, 'Tutorial', '', '{"url":"https://www.youtube.com/watch?v=i1_pQvKonRA&t=35s&#xA;Apply:","source":"xlsx"}'::jsonb, 'student');
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 2, 'link', true, '', '', '{"url":"https://www.passeport.ma/","label":"Apply for your passport","newTab":true,"internal":false,"source":"xlsx"}'::jsonb, 'student');

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'High School Diploma & Transcript' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 2, 'High School Diploma & Transcript', 'Prepare your original high school diploma and official transcript for university admission.', 'published', true, '{"documents":[{"key":"high_school_diploma_transcript","name":"High School Diploma & Transcript","description":"Prepare your original high school diploma and official transcript for university admission.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 2, description = 'Prepare your original high school diploma and official transcript for university admission.', status = 'published',
           required = true, rules = '{"documents":[{"key":"high_school_diploma_transcript","name":"High School Diploma & Transcript","description":"Prepare your original high school diploma and official transcript for university admission.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'paragraph', true, '', 'Get your original high school diploma and official transcript from your school. Make sure both documents are complete and in good condition. Tuturial : Apply :', '{"source":"xlsx"}'::jsonb, 'student');
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 1, 'link', true, '', '', '{"url":"https://www.apostille.ma/","label":"Apostille portal","newTab":true,"internal":false,"source":"xlsx"}'::jsonb, 'student');

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Diploma & Transcript Apostille' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 3, 'Diploma & Transcript Apostille', 'Get an apostille for your high school diploma and transcript to make them valid for international use.', 'published', true, '{"documents":[{"key":"diploma_transcript_apostille","name":"Diploma & Transcript Apostille","description":"Get an apostille for your high school diploma and transcript to make them valid for international use.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 3, description = 'Get an apostille for your high school diploma and transcript to make them valid for international use.', status = 'published',
           required = true, rules = '{"documents":[{"key":"diploma_transcript_apostille","name":"Diploma & Transcript Apostille","description":"Get an apostille for your high school diploma and transcript to make them valid for international use.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'paragraph', true, '', 'Watch the tutorial video, then apply through the official Apostille portal. Our support team can help you if you need guidance.', '{"source":"xlsx"}'::jsonb, 'student');

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'ranslate Diploma & Transcript' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 4, 'ranslate Diploma & Transcript', 'Have your high school diploma and official transcript translated by a certified translator into the required language: ENGLISH', 'published', true, '{"documents":[{"key":"ranslate_diploma_transcript","name":"ranslate Diploma & Transcript","description":"Have your high school diploma and official transcript translated by a certified translator into the required language: ENGLISH","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 4, description = 'Have your high school diploma and official transcript translated by a certified translator into the required language: ENGLISH', status = 'published',
           required = true, rules = '{"documents":[{"key":"ranslate_diploma_transcript","name":"ranslate Diploma & Transcript","description":"Have your high school diploma and official transcript translated by a certified translator into the required language: ENGLISH","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'paragraph', true, '', 'Find a certified translator in your city using this website. They can officially translate your diploma and transcript. Website:', '{"source":"xlsx"}'::jsonb, 'student');
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 1, 'link', true, '', '', '{"url":"https://atajtraduction.ma/ar/motarjim-mohalaf-fi-almaghrib/","label":"Find a certified translator","newTab":true,"internal":false,"source":"xlsx"}'::jsonb, 'student');

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'English Certificate' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 5, 'English Certificate', 'Prepare a valid English language certificate that meets your university''s admission requirements.', 'published', true, '{"documents":[{"key":"english_certificate","name":"English Certificate","description":"Prepare a valid English language certificate that meets your university''s admission requirements.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 5, description = 'Prepare a valid English language certificate that meets your university''s admission requirements.', status = 'published',
           required = true, rules = '{"documents":[{"key":"english_certificate","name":"English Certificate","description":"Prepare a valid English language certificate that meets your university''s admission requirements.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'program', true, '', '', '{"field":"english","source":"xlsx"}'::jsonb, 'student');
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 1, 'paragraph', true, '', 'Check your university''s required English test and prepare your certificate before applying.', '{"source":"xlsx"}'::jsonb, 'student');

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Motivation Letter' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 6, 'Motivation Letter', 'Write a clear motivation letter explaining why you want to study the program and why you are a good candidate.', 'published', true, '{"documents":[{"key":"motivation_letter","name":"Motivation Letter","description":"Write a clear motivation letter explaining why you want to study the program and why you are a good candidate.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 6, description = 'Write a clear motivation letter explaining why you want to study the program and why you are a good candidate.', status = 'published',
           required = true, rules = '{"documents":[{"key":"motivation_letter","name":"Motivation Letter","description":"Write a clear motivation letter explaining why you want to study the program and why you are a good candidate.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'paragraph', true, '', 'Keep it clear and honest.&#xA;Explain why you chose this program.&#xA;Share your study and career goals.&#xA;Check your grammar and spelling.&#xA;Do not copy from the internet.&#xA;Our support team will review your letter and approve it if it is ready.', '{"source":"xlsx"}'::jsonb, 'student');

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'CV (Resume)' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 7, 'CV (Resume)', 'Create an updated CV that highlights your academic background and relevant skills.', 'published', true, '{"documents":[{"key":"cv_resume","name":"CV (Resume)","description":"Create an updated CV that highlights your academic background and relevant skills.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 7, description = 'Create an updated CV that highlights your academic background and relevant skills.', status = 'published',
           required = true, rules = '{"documents":[{"key":"cv_resume","name":"CV (Resume)","description":"Create an updated CV that highlights your academic background and relevant skills.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'paragraph', true, '', 'Keep it to 1 page if possible.&#xA;Include your education and skills.&#xA;Add certificates and achievements.&#xA;Use a clean and simple format.&#xA;Check for spelling mistakes.&#xA;Our support team will review your resume and approve it if it is ready.', '{"source":"xlsx"}'::jsonb, 'student');

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Additional Courses' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 8, 'Additional Courses', 'Add any extra courses or certifications that strengthen your university application.', 'published', false, '{"documents":[{"key":"additional_courses","name":"Additional Courses","description":"Add any extra courses or certifications that strengthen your university application.","instructions":"","required":false,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":true,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 8, description = 'Add any extra courses or certifications that strengthen your university application.', status = 'published',
           required = false, rules = '{"documents":[{"key":"additional_courses","name":"Additional Courses","description":"Add any extra courses or certifications that strengthen your university application.","instructions":"","required":false,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":true,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'paragraph', true, '', 'Upload certificates from trusted platforms that are related to your chosen program or skills. Relevant courses can make your application stronger. Our support team will review your certificates and approve them if they are suitable.', '{"source":"xlsx"}'::jsonb, 'student');

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Personal Photo' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 9, 'Personal Photo', 'Prepare a recent passport-style photo that meets university and visa requirements.', 'published', true, '{"documents":[{"key":"personal_photo","name":"Personal Photo","description":"Prepare a recent passport-style photo that meets university and visa requirements.","instructions":"","required":true,"acceptedTypes":"pdf,jpg,jpeg,png","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 9, description = 'Prepare a recent passport-style photo that meets university and visa requirements.', status = 'published',
           required = true, rules = '{"documents":[{"key":"personal_photo","name":"Personal Photo","description":"Prepare a recent passport-style photo that meets university and visa requirements.","instructions":"","required":true,"acceptedTypes":"pdf,jpg,jpeg,png","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'paragraph', true, '', 'Use a recent, clear photo with a plain white background. Make sure your face is fully visible and the image is high quality. Our support team will review your photo and confirm that it meets the requirements.', '{"source":"xlsx"}'::jsonb, 'student');

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Application Fees' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 10, 'Application Fees', 'Prepare the required application fees before submitting your university application.', 'published', true, '{"documents":[],"allowSkip":false,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 10, description = 'Prepare the required application fees before submitting your university application.', status = 'published',
           required = true, rules = '{"documents":[],"allowSkip":false,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'program', true, '', '', '{"field":"app_fee","source":"xlsx"}'::jsonb, 'student');
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 1, 'paragraph', true, '', 'The application fee for your selected university is shown above. Make sure you prepare this amount before starting your application. Our support team can help you if you have any questions about the payment process.', '{"source":"xlsx"}'::jsonb, 'student');

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Submit Your Application' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 11, 'Submit Your Application', 'Submit your completed application and all required documents to your chosen university.', 'published', true, '{"documents":[{"key":"submit_your_application","name":"Submit Your Application","description":"Submit your completed application and all required documents to your chosen university.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 11, description = 'Submit your completed application and all required documents to your chosen university.', status = 'published',
           required = true, rules = '{"documents":[{"key":"submit_your_application","name":"Submit Your Application","description":"Submit your completed application and all required documents to your chosen university.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'paragraph', true, '', 'When every document is approved, open the university application page and submit your application there.', '{"plan":"self_service","source":"xlsx"}'::jsonb, 'student');
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 1, 'paragraph', true, '', 'Do not submit anything yourself. Our support team submits your university application on your behalf once all of your documents have been reviewed and approved.', '{"plan":"full_service","source":"xlsx"}'::jsonb, 'student');
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 2, 'paragraph', true, '', 'Before you submit, make sure all your documents are complete and approved. Once your application is submitted, the university will begin reviewing it.', '{"source":"xlsx"}'::jsonb, 'student');

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Motivational Interview' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 12, 'Motivational Interview', 'Complete the motivational interview to show your interest, goals, and readiness for the program.', 'published', true, '{"documents":[],"allowSkip":false,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 12, description = 'Complete the motivational interview to show your interest, goals, and readiness for the program.', status = 'published',
           required = true, rules = '{"documents":[],"allowSkip":false,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'list', true, 'How to prepare', '', '{"entries":["Be on time and test your microphone and camera before an online interview.","Dress appropriately and keep eye contact.","Speak clearly and answer honestly.","Explain why you chose this program.","Talk about your study and career goals.","Read every preparation PDF in this step before the interview.","Practise beforehand, and ask our support team if you need help."],"plan":"full_service","source":"xlsx"}'::jsonb, 'student');
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 1, 'paragraph', true, '', 'Participate in the university interview to discuss your motivation and future plans.', '{"source":"xlsx"}'::jsonb, 'student');

  /* ── Sage 2 : University Admission ── */
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'University Admission' limit 1;

  if v_stage is null then
    insert into public.journey_stages (country, plan, sort_order, title, description, icon, tone, status, rules)
    values ('LT', v_plan, 1, 'University Admission', '', 'graduation-cap', 'green', 'published', '{"degree":"Bachelor","source":"xlsx","excelStage":"Sage 2 : University Admission"}'::jsonb)
    returning id into v_stage;
  else
    update public.journey_stages
       set sort_order = 1, icon = 'graduation-cap', tone = 'green',
           status = 'published', rules = '{"degree":"Bachelor","source":"xlsx","excelStage":"Sage 2 : University Admission"}'::jsonb
     where id = v_stage;
  end if;


  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'University Review' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 0, 'University Review', 'Your application is being reviewed by the university admissions team.', 'published', true, '{"documents":[],"allowSkip":false,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 0, description = 'Your application is being reviewed by the university admissions team.', status = 'published',
           required = true, rules = '{"documents":[],"allowSkip":false,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'paragraph', true, '', 'Our team has submitted your application and we are waiting for the university''s admission decision. You do not need to do anything at this stage. If the university asks for more documents, an interview or any other information, our support team will contact you immediately.', '{"plan":"full_service","source":"xlsx"}'::jsonb, 'student');
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 1, 'paragraph', true, '', 'The review process may take several weeks. Check your email regularly for updates or requests from the university. Our support team will keep you informed about any important changes.', '{"source":"xlsx"}'::jsonb, 'student');

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Acceptance Letter' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 1, 'Acceptance Letter', 'Receive your official acceptance letter from the university after your application is approved.', 'published', true, '{"documents":[{"key":"acceptance_letter","name":"Acceptance Letter","description":"Receive your official acceptance letter from the university after your application is approved.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 1, description = 'Receive your official acceptance letter from the university after your application is approved.', status = 'published',
           required = true, rules = '{"documents":[{"key":"acceptance_letter","name":"Acceptance Letter","description":"Receive your official acceptance letter from the university after your application is approved.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'paragraph', true, '', 'Once the university accepts your application, you will receive an official acceptance letter. Keep this document safe, as you will need it for the next steps, including your visa application.', '{"source":"xlsx"}'::jsonb, 'student');

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Pay Tuition Fees' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 2, 'Pay Tuition Fees', 'Pay the required tuition fees according to your university''s payment instructions.', 'published', true, '{"documents":[{"key":"pay_tuition_fees","name":"Pay Tuition Fees","description":"Pay the required tuition fees according to your university''s payment instructions.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 2, description = 'Pay the required tuition fees according to your university''s payment instructions.', status = 'published',
           required = true, rules = '{"documents":[{"key":"pay_tuition_fees","name":"Pay Tuition Fees","description":"Pay the required tuition fees according to your university''s payment instructions.","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":10,"templatePath":"","templateName":"","notes":""}],"allowSkip":false,"source":"xlsx"}'::jsonb
     where id = v_step;
  end if;

  -- Content is fully owned by the import, so it is replaced wholesale. Nothing
  -- references a block id, unlike steps, so this is safe.
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 0, 'program', true, '', '', '{"field":"tuition","source":"xlsx"}'::jsonb, 'student');
  insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
    values (v_step, 1, 'paragraph', true, '', 'We recommend using Attijariwafa Bank or BMCE Bank for your international tuition payment.&#xA;&#xA;Bring the following documents to the bank and ask the staff to process an international tuition fee payment.&#xA;&#xA;Required documents:&#xA;&#xA;Copy of your passport&#xA;Copy of your national ID card&#xA;University acceptance letter&#xA;Tuition invoice (PDF) &#xA;&#xA;After you complete the payment, upload your paid invoice through the platform''s Payment section. Our team will review and approve your payment. If you need any help, please contact our support team.', '{"source":"xlsx"}'::jsonb, 'student');

  /* ── Stage 3 : MIGRIS Application ── */
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'MIGRIS Application' limit 1;

  if v_stage is null then
    insert into public.journey_stages (country, plan, sort_order, title, description, icon, tone, status, rules)
    values ('LT', v_plan, 2, 'MIGRIS Application', '', 'file-text', 'amber', 'draft', '{"degree":"Bachelor","source":"xlsx","excelStage":"Stage 3 : MIGRIS Application"}'::jsonb)
    returning id into v_stage;
  else
    update public.journey_stages
       set sort_order = 2, icon = 'file-text', tone = 'amber',
           status = 'draft', rules = '{"degree":"Bachelor","source":"xlsx","excelStage":"Stage 3 : MIGRIS Application"}'::jsonb
     where id = v_stage;
  end if;


end loop;
end $$;

notify pgrst, 'reload schema';
