-- 19 · Verification for the LT Bachelor journey content.
--
-- Generated by scripts/import-journey.mjs — do not hand-edit. Re-run the script
-- after the Excel changes, apply 12_journey_content_lt_bachelor.sql, then run
-- this and read the status column.
--
-- Source: /home/szei/Documents/Important-AW/Bachelor-Journey-stages-lt.xlsx
-- Expects, for EACH of self_service and full_service:
--   5 stages · 55 steps · 42 documents · 163 learn blocks
--
-- EVERY ROW OF QUERY 1 MUST READ 'OK'. Anything else names the stage and the
-- plan it went wrong on.
--
-- Only rows the import owns are counted: stages and steps tagged
-- rules ->> 'source' = 'xlsx', and blocks tagged data ->> 'source' = 'xlsx'.
-- A stage, step or block an administrator adds by hand is therefore ignored
-- here rather than reported as a mismatch — this checks the Excel's content,
-- not everything that happens to exist.

-- ── 1 · Per stage, per plan ────────────────────────────────────────────────
with expected (stage_title, sort_order, steps, docs, blocks) as (
  values
    ('Pre-Application', 0, 13, 10, 26),
    ('University Admission', 1, 4, 3, 10),
    ('migration Application Preparation', 2, 19, 29, 28),
    ('VFS Appointment & Biometrics', 3, 6, 0, 39),
    ('Arrival in Lithuania', 4, 13, 0, 60)
),
plans (plan) as (
  values ('self_service'), ('full_service')
),
want as (
  select p.plan, e.* from plans p cross join expected e
),
step_facts as (
  select s.plan,
         s.title as stage_title,
         st.id   as step_id,
         coalesce(jsonb_array_length(st.rules -> 'documents'), 0) as docs
    from public.journey_stages s
    left join public.journey_steps st
           on st.stage_id = s.id
          and st.status = 'published'
          and (st.rules ->> 'source') = 'xlsx'
   where s.country = 'LT'
     and s.status = 'published'
     and (s.rules ->> 'source') = 'xlsx'
),
block_counts as (
  select step_id, count(*) as n
    from public.journey_blocks
   where (data ->> 'source') = 'xlsx'
   group by step_id
),
actual as (
  select f.plan,
         f.stage_title,
         count(f.step_id)                        as steps,
         coalesce(sum(f.docs), 0)                as docs,
         coalesce(sum(coalesce(b.n, 0)), 0)      as blocks
    from step_facts f
    left join block_counts b on b.step_id = f.step_id
   group by f.plan, f.stage_title
)
select
  coalesce(w.plan, a.plan)                                as plan,
  coalesce(w.sort_order + 1, 0)                           as stage,
  coalesce(w.stage_title, a.stage_title)                  as stage_title,
  coalesce(a.steps,  0) || ' / ' || coalesce(w.steps,  0) as steps_got_want,
  coalesce(a.docs,   0) || ' / ' || coalesce(w.docs,   0) as docs_got_want,
  coalesce(a.blocks, 0) || ' / ' || coalesce(w.blocks, 0) as blocks_got_want,
  case
    when a.stage_title is null then 'MISSING STAGE'
    when w.stage_title is null then 'UNEXPECTED STAGE'
    when a.steps = w.steps and a.docs = w.docs and a.blocks = w.blocks then 'OK'
    else 'MISMATCH'
  end                                                     as status
  from want w
  full outer join actual a
    on a.plan = w.plan and a.stage_title = w.stage_title
 order by plan, stage;

-- ── 2 · Totals per plan ────────────────────────────────────────────────────
-- Expect 55 steps, 42 documents and 163 blocks on each plan.
select s.plan,
       count(distinct s.id)  as stages,
       count(st.id)          as steps,
       coalesce(sum(coalesce(jsonb_array_length(st.rules -> 'documents'), 0)), 0) as documents,
       coalesce((select count(*) from public.journey_blocks b
                  join public.journey_steps s2 on s2.id = b.step_id
                  join public.journey_stages g on g.id = s2.stage_id
                 where g.plan = s.plan and g.country = 'LT'
                   and g.status = 'published' and (g.rules ->> 'source') = 'xlsx'
                   and s2.status = 'published' and (s2.rules ->> 'source') = 'xlsx'
                   and (b.data ->> 'source') = 'xlsx'), 0) as learn_blocks
  from public.journey_stages s
  left join public.journey_steps st
         on st.stage_id = s.id and st.status = 'published' and (st.rules ->> 'source') = 'xlsx'
 where s.country = 'LT' and s.status = 'published' and (s.rules ->> 'source') = 'xlsx'
 group by s.plan
 order by s.plan;

-- ── 3 · Message templates ──────────────────────────────────────────────────
-- journey_emit() reads these. Empty means every automated notification, chat
-- message and WhatsApp message silently does nothing.
select event, string_agg(channel, ', ' order by channel) as channels
  from public.journey_templates
 group by event
 order by event;

-- ── 4 · Nothing stale left published ───────────────────────────────────────
-- An earlier import's stage that the Excel no longer lists must be archived.
-- This should return NO rows.
select plan, title, status
  from public.journey_stages
 where country = 'LT'
   and status = 'published'
   and (rules ->> 'source') = 'xlsx'
   and title not in ('Pre-Application', 'University Admission', 'migration Application Preparation', 'VFS Appointment & Biometrics', 'Arrival in Lithuania')
 order by plan, title;
