-- 21 · Optional Sponsorship module for "migration Application Preparation".
--
-- Generated by scripts/emit-module-chunk.mjs — do not hand-edit. The steps are
-- declared in scripts/journey-modules.mjs and are part of the normal import, so
-- re-running scripts/import-journey.mjs keeps them rather than archiving them.
--
-- Steps: 6 (1 container + 5 children)
--
-- These steps exist for every student but stay hidden, uncounted and inert
-- until the student switches the module on; enablement is one flag on the
-- container's own journey_progress row, so nothing here is per-student.
--
-- Learn content is deliberately empty: administrators populate it from the
-- Journey Manager, and nothing in the platform needs it to be there first.

do $mod$
declare
  v_plan  text;
  v_stage uuid;
  v_step  uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop

  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'migration Application Preparation' limit 1;
  if v_stage is null then continue; end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Financial Sponsorship' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 13, 'Financial Sponsorship', 'Need someone to financially support your studies? Enable this optional module to prepare and upload all sponsorship documents required for your application. This module is only required for students applying with a financial sponsor.', 'published', true, '{"documents":[],"source":"module","module":"sponsorship","optionalModule":true,"icon":"handshake","dialogs":{"enable":{"title":"Enable Financial Sponsorship?","body":"You are about to enable the Financial Sponsorship module. Additional document steps will be added to your Stage 3 journey. Only enable this feature if you are applying with a financial sponsor.","confirmLabel":"Start"},"disable":{"title":"Disable Sponsorship Module?","body":"Disabling this module will remove all sponsorship steps from your journey. Previously uploaded documents will remain stored in the Documents Module unless removed separately.","confirmLabel":"Disable"},"remind":{"title":"Need Financial Sponsorship?","body":"If someone will financially support your studies, you can still enable the optional sponsorship module and upload the required documents.","confirmLabel":"Start","dismissLabel":"No Thanks"}},"completion":"module"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 13, description = 'Need someone to financially support your studies? Enable this optional module to prepare and upload all sponsorship documents required for your application. This module is only required for students applying with a financial sponsor.', status = 'published',
           required = true, rules = '{"documents":[],"source":"module","module":"sponsorship","optionalModule":true,"icon":"handshake","dialogs":{"enable":{"title":"Enable Financial Sponsorship?","body":"You are about to enable the Financial Sponsorship module. Additional document steps will be added to your Stage 3 journey. Only enable this feature if you are applying with a financial sponsor.","confirmLabel":"Start"},"disable":{"title":"Disable Sponsorship Module?","body":"Disabling this module will remove all sponsorship steps from your journey. Previously uploaded documents will remain stored in the Documents Module unless removed separately.","confirmLabel":"Disable"},"remind":{"title":"Need Financial Sponsorship?","body":"If someone will financially support your studies, you can still enable the optional sponsorship module and upload the required documents.","confirmLabel":"Start","dismissLabel":"No Thanks"}},"completion":"module"}'::jsonb
     where id = v_step;
  end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Affidavit / Sponsorship Letter' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 14, 'Affidavit / Sponsorship Letter', 'Provide the official sponsorship letter containing the sponsor''s personal information, relationship to you, and sponsorship period.', 'published', true, '{"documents":[{"key":"affidavit_sponsorship_letter","name":"Affidavit / Sponsorship Letter","description":"","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""}],"source":"module","moduleOf":"sponsorship","completion":"self","cta":"Done"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 14, description = 'Provide the official sponsorship letter containing the sponsor''s personal information, relationship to you, and sponsorship period.', status = 'published',
           required = true, rules = '{"documents":[{"key":"affidavit_sponsorship_letter","name":"Affidavit / Sponsorship Letter","description":"","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""}],"source":"module","moduleOf":"sponsorship","completion":"self","cta":"Done"}'::jsonb
     where id = v_step;
  end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Sponsor''s Passport / ID' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 15, 'Sponsor''s Passport / ID', 'Upload your sponsor''s passport and residency document (Green Card if applicable).', 'published', true, '{"documents":[{"key":"sponsor_s_passport","name":"Sponsor''s Passport","description":"","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""},{"key":"sponsor_s_residency_document_if_applicab","name":"Sponsor''s Residency Document (if applicable)","description":"","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""}],"source":"module","moduleOf":"sponsorship","completion":"self","cta":"Done"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 15, description = 'Upload your sponsor''s passport and residency document (Green Card if applicable).', status = 'published',
           required = true, rules = '{"documents":[{"key":"sponsor_s_passport","name":"Sponsor''s Passport","description":"","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""},{"key":"sponsor_s_residency_document_if_applicab","name":"Sponsor''s Residency Document (if applicable)","description":"","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""}],"source":"module","moduleOf":"sponsorship","completion":"self","cta":"Done"}'::jsonb
     where id = v_step;
  end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Bank Maintenance (Translated)' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 16, 'Bank Maintenance (Translated)', 'Upload the translated bank maintenance or bank statement document provided by your sponsor.', 'published', true, '{"documents":[{"key":"bank_maintenance_translated","name":"Bank Maintenance (Translated)","description":"","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""}],"source":"module","moduleOf":"sponsorship","completion":"self","cta":"Done"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 16, description = 'Upload the translated bank maintenance or bank statement document provided by your sponsor.', status = 'published',
           required = true, rules = '{"documents":[{"key":"bank_maintenance_translated","name":"Bank Maintenance (Translated)","description":"","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""}],"source":"module","moduleOf":"sponsorship","completion":"self","cta":"Done"}'::jsonb
     where id = v_step;
  end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Your & Sponsor''s Unabridged Copy' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 17, 'Your & Sponsor''s Unabridged Copy', 'Upload the required unabridged copies proving your relationship with the sponsor.', 'published', true, '{"documents":[{"key":"your_unabridged_copy","name":"Your Unabridged Copy","description":"","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""},{"key":"sponsor_s_unabridged_copy","name":"Sponsor''s Unabridged Copy","description":"","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""}],"source":"module","moduleOf":"sponsorship","completion":"self","cta":"Done"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 17, description = 'Upload the required unabridged copies proving your relationship with the sponsor.', status = 'published',
           required = true, rules = '{"documents":[{"key":"your_unabridged_copy","name":"Your Unabridged Copy","description":"","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""},{"key":"sponsor_s_unabridged_copy","name":"Sponsor''s Unabridged Copy","description":"","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""}],"source":"module","moduleOf":"sponsorship","completion":"self","cta":"Done"}'::jsonb
     where id = v_step;
  end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Proof of Sponsor''s Employment' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 18, 'Proof of Sponsor''s Employment', 'Upload official employment documents that prove your sponsor is currently employed and has a stable source of income. These documents help demonstrate the sponsor''s financial ability to support your studies.', 'published', false, '{"documents":[{"key":"employment_verification_letter","name":"Employment Verification Letter","description":"","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""},{"key":"employment_contract","name":"Employment Contract","description":"","instructions":"","required":false,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""},{"key":"recent_salary_slips_payslips","name":"Recent Salary Slips / Payslips","description":"","instructions":"","required":false,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""},{"key":"employer_certificate","name":"Employer Certificate","description":"","instructions":"","required":false,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""}],"source":"module","moduleOf":"sponsorship","completion":"self","cta":"Done","allowSkip":true,"confirm":{"title":"Skip employment proof?","question":"You can continue without these documents and add them later. Your journey will show this step as skipped.","confirmLabel":"Yes, skip for now"}}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 18, description = 'Upload official employment documents that prove your sponsor is currently employed and has a stable source of income. These documents help demonstrate the sponsor''s financial ability to support your studies.', status = 'published',
           required = false, rules = '{"documents":[{"key":"employment_verification_letter","name":"Employment Verification Letter","description":"","instructions":"","required":true,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""},{"key":"employment_contract","name":"Employment Contract","description":"","instructions":"","required":false,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""},{"key":"recent_salary_slips_payslips","name":"Recent Salary Slips / Payslips","description":"","instructions":"","required":false,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""},{"key":"employer_certificate","name":"Employer Certificate","description":"","instructions":"","required":false,"acceptedTypes":"pdf","maxSizeMb":4,"templatePath":"","templateName":"","notes":""}],"source":"module","moduleOf":"sponsorship","completion":"self","cta":"Done","allowSkip":true,"confirm":{"title":"Skip employment proof?","question":"You can continue without these documents and add them later. Your journey will show this step as skipped.","confirmLabel":"Yes, skip for now"}}'::jsonb
     where id = v_step;
  end if;

end loop;
end $mod$;

notify pgrst, 'reload schema';
