-- Stage 5 chunk 00 · the stage · generated by scripts/emit-stage5-chunks.mjs — do not hand-edit.

do $s5$
declare v_plan text; v_stage uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'Arrival in Lithuania' limit 1;
  if v_stage is null then
    insert into public.journey_stages (country, plan, sort_order, title, description, icon, tone, status, rules)
    values ('LT', v_plan, 4, 'Arrival in Lithuania', '',
            'plane', 'teal', 'published', '{"degree":"Bachelor","source":"xlsx","authored":"stage5","requiresPlan":"full_service"}'::jsonb);
  else
    update public.journey_stages
       set sort_order = 4, description = '',
           icon = 'plane', tone = 'teal', status = 'published', rules = '{"degree":"Bachelor","source":"xlsx","authored":"stage5","requiresPlan":"full_service"}'::jsonb
     where id = v_stage;
  end if;
end loop;
end $s5$;
