-- Stage 5 chunk 01 · Congratulations! Welcome to Lithuania 🎉 · generated by scripts/emit-stage5-chunks.mjs — do not hand-edit.

do $s5$
declare v_plan text; v_stage uuid; v_step uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'Arrival in Lithuania' limit 1;
  if v_stage is null then continue; end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Congratulations! Welcome to Lithuania 🎉' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 0, 'Congratulations! Welcome to Lithuania 🎉', 'Congratulations on successfully receiving your Temporary Residence Permit and arriving safely in Lithuania. You have officially started your new academic journey. If you need help with accommodation, university procedures, documents, banking, healthcare, transportation, or everyday life, the AfaqWay Support Team is ready to assist you. Complete this support step to unlock the remaining onboarding journey.', 'published', true, '{"documents":[],"source":"xlsx","cta":"Chat with Support","support":true,"approveOnly":true}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 0, description = 'Congratulations on successfully receiving your Temporary Residence Permit and arriving safely in Lithuania. You have officially started your new academic journey. If you need help with accommodation, university procedures, documents, banking, healthcare, transportation, or everyday life, the AfaqWay Support Team is ready to assist you. Complete this support step to unlock the remaining onboarding journey.', status = 'published',
           required = true, rules = '{"documents":[],"source":"xlsx","cta":"Chat with Support","support":true,"approveOnly":true}'::jsonb
     where id = v_step;
  end if;

  /* Same tag the full migration uses. Deleting on a tag the blocks do not
     carry would match nothing, so re-running a chunk would append a second copy
     of every module instead of replacing them. Blocks an administrator added by
     hand carry no source tag and survive, exactly as in the full migration. */
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';

      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 0, 'module', true, 'Welcome to Your New Journey', 'You made it. Getting a Temporary Residence Permit and moving to another country is genuinely hard, and you have already done the hardest part.

The next few weeks are about turning a place you have arrived in into a place you live. This stage walks you through that, one task at a time.

## What your first week usually looks like

- **Day 1** — get to your accommodation, buy a Lithuanian SIM card, get some cash or check your card works, eat, sleep.
- **Days 2-3** — find the nearest supermarket and pharmacy, work out how to reach your university, get a public transport card.
- **Days 4-7** — go to your university''s international office, complete enrolment, collect your student ID, and start your residence declaration.

Do not try to do everything on the first day. Almost nothing here has a same-week deadline except your residence declaration, and we will remind you about that one.

## How this stage is organised

Each step below is a small, self-contained job with a Learn section that explains it and a **Done** button you press when you have finished. You can work through them in any order once this first step is approved.

Some steps are urgent, some can wait:

| Do first | Can wait a week or two |
| --- | --- |
| SIM card, university enrolment, residence registration | Banking, healthcare registration, transport card |
| | Finding a job, social activities, study habits |

## How AfaqWay keeps supporting you

Your relationship with us does not end when you land. Press **Chat with Support** on this step and a real person from our team will contact you on WhatsApp. Use it whenever something is confusing, not only when something is wrong.

> [!TIP] There is no such thing as a question that is too small. "Which bus goes to campus?" is a perfectly good reason to message us.

## What you''ll accomplish in this stage

- [ ] Talk to the AfaqWay support team and unlock the rest of this stage
- [ ] Find safe, affordable accommodation and understand your rental contract
- [ ] Complete your first-week arrival checklist
- [ ] Get a Lithuanian phone number
- [ ] Finish your university enrolment and collect your student ID
- [ ] Declare your place of residence
- [ ] Open a Lithuanian bank account
- [ ] Understand how to see a doctor
- [ ] Get a student public transport card
- [ ] Build a realistic monthly budget
- [ ] Find part-time work, if you want it
- [ ] Meet people and settle into life here
- [ ] Set up study habits that will carry you through your degree', '{"summary":"What to expect in your first days in Lithuania, and how this stage will help you settle in.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 1, 'module', true, 'When to Contact Support', 'Knowing when to ask for help saves you days. Here is how we think about it.

## Message us straight away

These are situations where a delay costs you money, time or legal standing:

- **Residence registration problems** — you have been refused, or you are close to the one-month deadline.
- **Anything official you do not understand** — a letter from the Migration Department, the municipality, or Sodra.
- **Accommodation gone wrong** — a landlord asking for money before a viewing, refusing a written contract, or keeping your deposit.
- **University enrolment blocked** — a missing or rejected document, or a deadline you cannot meet.
- **Bank account refused** — this is common and usually fixable, but it needs the right paperwork.
- **You are unwell and do not know where to go.**
- **Any request for payment you were not expecting.**

## You can usually handle these yourself

The Learn sections in this stage cover all of them:

- Buying a SIM card or topping it up
- Getting a public transport card and finding a bus route
- Everyday shopping, deliveries, and finding your way around
- Registering for a student club or event
- Setting up mobile banking once your account exists

> [!IMPORTANT] In a real emergency — a threat to life, health or safety — call **112** first, then tell us. 112 is free, works from any phone, and operators speak English.

## How to ask well

You will get a faster answer if your first message includes:

1. What you are trying to do
2. What happened instead
3. A photo of any document or error message
4. Your city and university

## Checklist

- [ ] Save the AfaqWay support number in your phone
- [ ] Save **112** in your phone
- [ ] Save your university''s international office number
- [ ] Press **Chat with Support** below to start the conversation', '{"summary":"Which situations you can handle yourself, and when to message the AfaqWay team.","source":"xlsx"}'::jsonb, 'student');
end loop;
end $s5$;
