-- Stage 5 chunk 02 · Accommodation · generated by scripts/emit-stage5-chunks.mjs — do not hand-edit.

do $s5$
declare v_plan text; v_stage uuid; v_step uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'Arrival in Lithuania' limit 1;
  if v_stage is null then continue; end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Accommodation' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 1, 'Accommodation', 'Finding safe and affordable accommodation is one of the first priorities after arriving in Lithuania. This step teaches you how to search for housing, compare options, understand rental agreements, and avoid common scams before signing a contract.', 'published', true, '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 1, description = 'Finding safe and affordable accommodation is one of the first priorities after arriving in Lithuania. This step teaches you how to search for housing, compare options, understand rental agreements, and avoid common scams before signing a contract.', status = 'published',
           required = true, rules = '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb
     where id = v_step;
  end if;

  /* Same tag the full migration uses. Deleting on a tag the blocks do not
     carry would match nothing, so re-running a chunk would append a second copy
     of every module instead of replacing them. Blocks an administrator added by
     hand carry no source tag and survive, exactly as in the full migration. */
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';

      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 0, 'module', true, 'Understanding Your Accommodation Options', 'There are five realistic options. Most students start with one and move to another after a few months.

## University dormitory

- **Cost** — usually the cheapest option, and billed monthly through the university.
- **Advantages** — no deposit games, no landlord, contract in English, other students around you, usually close to campus.
- **Disadvantages** — shared rooms or shared kitchens are common, limited places, and you often cannot choose your roommate.
- **Best for** — almost every new international student, for the first semester.

## Private student residence

- **Advantages** — modern buildings, private rooms, bills included, English-speaking staff.
- **Disadvantages** — more expensive than a dormitory; places fill early.
- **Best for** — students who want their own room without the risk of a private landlord.

## Shared apartment (a room in a flat)

- **Advantages** — cheaper than renting alone, and an easy way to meet people.
- **Disadvantages** — you inherit your flatmates and whatever contract already exists.
- **Best for** — the second semester onward, once you know the city.

## Private apartment

- **Advantages** — complete independence.
- **Disadvantages** — most expensive, needs a deposit, and the contract will often be in Lithuanian.
- **Best for** — students arriving with family, or in their second year.

## Temporary accommodation

A hostel or short-let for your first week, while you view places in person.

> [!TIP] Booking two weeks of temporary accommodation is not wasted money. It is what lets you refuse a bad apartment instead of signing it because you have nowhere to sleep.

## What things cost

Indicative monthly ranges for Vilnius as of early 2026. Kaunas, Klaipėda and Šiauliai are typically cheaper.

| Option | Typical monthly cost |
| --- | --- |
| University dormitory | Lowest — check your university''s page |
| Room in a shared flat | around €280 |
| Studio apartment | around €460 |
| One-bedroom, city centre | €550-850 |

Always add utilities (heating, electricity, water, internet) unless the advert says they are included. Heating in winter is the item that surprises people.

## Recommended order

1. **Apply for a university dormitory** as early as you can — before you fly, if possible.
2. **Book temporary accommodation** for your first one to two weeks.
3. **Search verified long-term rentals** and view them in person.
4. **Sign only after a viewing**, with a written contract.

## Checklist

- [ ] Check whether your university still has dormitory places
- [ ] Book temporary accommodation for your first week
- [ ] Decide your maximum monthly budget, including utilities
- [ ] Shortlist three places to view in person', '{"summary":"The housing options open to international students, and which suits you best.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 1, 'module', true, 'Safe Apartment Search', '## The main platforms

**[Aruodas.lt](https://en.aruodas.lt/)** — the largest property portal in Lithuania, with an English interface. Most serious long-term listings appear here first.

**[Skelbiu.lt](https://www.skelbiu.lt/)** — a large general classifieds site with a big rental section. More private landlords, fewer agencies.

**[Domoplius.lt](https://www.domoplius.lt/)** — a third portal worth checking; listings often overlap with Aruodas.

## How to search effectively

1. Set your **maximum price** and tick whether utilities are included.
2. Filter by **district**, not just city — then check the commute to your campus on Google Maps before you contact anyone.
3. Sort by **newest**. Good rentals in Vilnius are taken within days.
4. Save the search and check it every morning during your search week.

## How to contact a landlord

- Write in simple English. Most landlords in Vilnius and Kaunas manage.
- Say who you are in one line: *"I am an international student at [university], starting in September, looking for a long-term rental."*
- Ask three questions: is it still available, are utilities included, and when can you view it.

## Reading a listing properly

- **Photos** — too few, or clearly from a different season, is a bad sign.
- **Price against the table above** — anything far below market is bait.
- **Address** — a real listing names at least the district and street.

## Facebook Marketplace and Facebook groups

You will be pointed at student housing groups on Facebook. They do contain real rooms.

> [!WARNING] Facebook groups carry a much higher scam risk than Aruodas or Skelbiu. There is no verification, listings cannot be reported to a portal, and money sent to a stranger cannot be recovered. Treat anything found there with extra caution and never pay before a viewing.

## Checklist

- [ ] Create a saved search on Aruodas
- [ ] Create a saved search on Skelbiu
- [ ] Check the commute for every place before contacting the landlord
- [ ] Contact at least five listings — most will not reply', '{"summary":"Where Lithuanians actually look for rentals, and how to search them effectively.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 2, 'module', true, 'Avoiding Rental Scams', 'International students are targeted because you are arranging housing from abroad, in a hurry, in a language you may not read. Every scam below relies on one thing: getting money before you see the apartment.

## The five common scams

**1. The listing that does not exist.** Photos stolen from a real advert, priced well below market, "available immediately".

**2. Deposit before viewing.** You are asked to "reserve" the flat. Once you pay, contact stops.

**3. The landlord who is abroad.** A convincing story about working in another country, so a viewing is "impossible", but they will "post the keys" after payment.

**4. Fake identity documents.** A scanned passport or ownership certificate sent to reassure you. Scans prove nothing.

**5. Invented fees.** "Agency processing fee", "reservation fee", "guarantee fee" — charges that do not exist in a normal Lithuanian rental.

## Warning signs

- Rent far below the ranges in the first module
- Pressure to decide today
- Refusal to do a video call, let alone a viewing
- Payment by Western Union, gift card, crypto, or to a personal account in another country
- The contract is refused, or only offered "after payment"
- The person''s name does not match the ownership documents

## Safe practice

> [!IMPORTANT] Never pay a deposit or rent before you have seen the property in person and signed a written contract. There is no exception to this rule, however good the apartment looks.

- View in person. If you are still abroad, ask a friend, or wait until you arrive — this is exactly why you book temporary accommodation.
- Ask to see the owner''s **ID and proof of ownership** and check the name matches the contract.
- Pay by **bank transfer only**, to a Lithuanian account in the landlord''s name, once the contract is signed.
- Get a **receipt** for the deposit.
- Keep every message. A written trail is what makes a complaint possible.

## If you think you have been scammed

1. Stop paying immediately.
2. Contact your bank — a very recent transfer can sometimes be recalled.
3. Report it to the police by calling **112** or at your local station.
4. Message AfaqWay Support so we can help you with the report and find you somewhere to stay.

## Checklist

- [ ] I have seen the apartment in person
- [ ] I have seen the landlord''s ID and proof of ownership
- [ ] I have a written contract in a language I can read
- [ ] I am paying by bank transfer to a Lithuanian account
- [ ] I have not paid anything before signing', '{"summary":"The scams that target international students, and how to shut each one down.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 3, 'module', true, 'Signing Your Rental Agreement', 'A written contract protects you far more than it protects the landlord. Never rent without one.

## What the contract must state

- **Full names** of both parties, and the landlord''s personal or company code
- **The exact address**, including apartment number
- **The monthly rent**, and the date it is due
- **The deposit amount** and the conditions for returning it
- **Which utilities are included** and which you pay separately
- **The contract length** and the notice period for ending it
- **An inventory** of furniture and appliances, with their condition

## The deposit

- Usually one month''s rent, sometimes two.
- It is returned at the end of the contract, minus **documented** damage.
- Normal wear and tear is not damage.
- Photograph every room, including existing marks and scratches, on the day you move in, and email the photos to the landlord so they are timestamped.

## Utilities

Ask specifically whether the rent includes heating. Lithuanian winters are cold and heating is the largest variable bill, typically much higher between November and March. Also confirm electricity, water, internet and the building maintenance fee.

## Who is responsible for what

| Landlord | Tenant |
| --- | --- |
| Structural repairs, heating system, plumbing | Everyday cleaning and small repairs |
| Appliances that fail through normal use | Damage you or your guests cause |
| Registering the apartment for your residence declaration, if agreed | Paying rent and bills on time |

> [!MISTAKE] Signing a Lithuanian-only contract you cannot read. Ask for an English version or a translation. If the landlord refuses, that alone is a reason to walk away — and a good moment to message AfaqWay Support.

## Checklist before signing

- [ ] Names and address are correct
- [ ] Rent, due date and deposit are written down
- [ ] It says clearly which utilities are included
- [ ] Contract length and notice period are stated
- [ ] An inventory is attached
- [ ] I have move-in photos of every room
- [ ] I have a copy of the signed contract
- [ ] The landlord agrees to let me declare my residence at this address', '{"summary":"What a Lithuanian rental contract should contain, and what to check before you sign.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 4, 'module', true, 'Practical Tips', '## When to search

- **July and August** are the busiest months, because every student is looking. Start early.
- **Mid-semester** (October, February) is quieter and prices soften.
- Dormitory applications usually open months before the semester — check your university''s page now, not later.

## Choosing a district

Do not optimise for rent alone. A cheaper flat 45 minutes from campus costs you two hours a day and a transport card you use constantly. Check the door-to-door commute before you fall in love with a listing.

## Moving in

- **Furniture** — most Lithuanian rentals come furnished. If yours does not, IKEA delivers in Lithuania, and second-hand furniture is easy to find on Skelbiu.
- **Internet** — Telia, Bitė and Cgates all offer home broadband. Ask the landlord what is already installed; reusing an existing connection is much faster than a new installation.
- **Bedding and kitchen basics** are rarely included. Budget for one shopping trip in your first week.

## Winter, honestly

Lithuanian winters are long and dark. A flat with good heating and daylight matters more in January than it seems in September. Ask about window quality and heating type before signing.

## Accommodation Preparation Checklist

- [ ] Dormitory application submitted, or a decision made not to
- [ ] Temporary accommodation booked for arrival
- [ ] Budget set, including utilities
- [ ] Commute checked for each shortlisted place
- [ ] Viewings arranged in person
- [ ] Contract read, understood and signed
- [ ] Move-in photos taken
- [ ] Internet arranged
- [ ] Landlord agrees to the residence declaration', '{"summary":"Timing, districts, furniture and internet — the practical details that make a search work.","source":"xlsx"}'::jsonb, 'student');
end loop;
end $s5$;
