-- Stage 5 chunk 03 · Arrived in Lithuania · generated by scripts/emit-stage5-chunks.mjs — do not hand-edit.

do $s5$
declare v_plan text; v_stage uuid; v_step uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'Arrival in Lithuania' limit 1;
  if v_stage is null then continue; end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Arrived in Lithuania' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 2, 'Arrived in Lithuania', 'Congratulations on arriving safely. This step helps you complete your first arrival checklist and become familiar with your new environment.', 'published', true, '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 2, description = 'Congratulations on arriving safely. This step helps you complete your first arrival checklist and become familiar with your new environment.', status = 'published',
           required = true, rules = '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb
     where id = v_step;
  end if;

  /* Same tag the full migration uses. Deleting on a tag the blocks do not
     carry would match nothing, so re-running a chunk would append a second copy
     of every module instead of replacing them. Blocks an administrator added by
     hand carry no source tag and survive, exactly as in the full migration. */
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';

      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 0, 'module', true, 'First Day Checklist', 'Your first day has one goal: get safely to where you are sleeping, with a working phone and a way to pay for things. Everything else can wait.

## In order

1. **Passport control** — have your passport and your TRP or visa ready, plus your acceptance letter and accommodation address in case you are asked.
2. **Collect your luggage** and check nothing is missing before leaving the baggage hall.
3. **Get connected** — airport Wi-Fi first, then buy a Lithuanian SIM card (Step 4 covers which one).
4. **Cash or card** — Lithuania is close to cashless; contactless cards work almost everywhere, including on buses. Withdraw €50-100 for the rare cash-only situation.
5. **Travel to your accommodation** — public transport or a booked taxi. Do not accept an unofficial ride offered to you inside the terminal.
6. **Check in** and confirm you can get back in if you go out.
7. **Eat something** and buy water, bread and breakfast for the morning.
8. **Message your family** that you arrived.
9. **Lay out your university documents** for tomorrow — originals, not copies.

> [!TIP] Keep your passport, TRP, acceptance letter and rental contract together in one folder for your first month. You will be asked for them more often than you expect.

## First Day Checklist

- [ ] Cleared passport control
- [ ] Collected all luggage
- [ ] Lithuanian SIM card bought and working
- [ ] Some cash withdrawn
- [ ] Arrived at accommodation
- [ ] Food and water for tomorrow
- [ ] Family told you arrived safely
- [ ] University documents ready', '{"summary":"What to do in your first 24 hours, in order.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 1, 'module', true, 'Airport Guide', 'Most students arrive at **Vilnius Airport (VNO)**, some at Kaunas (KUN) or Palanga (PLQ).

## Arrivals, step by step

- **Passport control** — as a non-EU national you use the "All passports" lane. Have your TRP or visa, acceptance letter and accommodation address ready.
- **Baggage claim** — screens show your flight and belt number.
- **Customs** — green channel if you have nothing to declare. Cash of €10,000 or more must be declared.
- **Wi-Fi** — free at Vilnius Airport.
- **Currency exchange and ATMs** — available in Arrivals. Airport exchange rates are poor; withdraw from an ATM instead and change only what you need.

## From Vilnius Airport to the city

Buses leave from directly outside Arrivals.

- **Bus 3G** — Airport → city centre → Fabijoniškės
- **Bus 1** — Airport → central bus and railway stations (*Stotis*)
- Buses run roughly every 15-30 minutes and reach the centre in about 15 minutes
- A single ticket bought on board costs about **€1**, paid by contactless card at the validator
- You can also buy a transport card at the *Narvesen* shop in the terminal

There is also a short train link between the airport and the central railway station.

**Official page:** [Vilnius Airport — public transport](https://www.vilnius-airport.lt/en/before-the-flight/transport/by-public-transport) and [JUDU — Vilnius Airport by public transport](https://judu.lt/en/for-public-transport-passengers/vilnius-airport-by-public-transport/)

## Taxis

Use an app rather than a taxi rank: **Bolt** and **Uber** both operate in Lithuania, show the price before you accept, and keep a record of the trip.

> [!WARNING] Never accept a ride from someone who approaches you inside the terminal offering a taxi. Book through an app or use the official rank outside.

## Checklist

- [ ] Documents ready before passport control
- [ ] Connected to airport Wi-Fi
- [ ] Transport into the city decided before landing
- [ ] Bolt or Uber installed as a backup', '{"summary":"Getting through a Lithuanian airport and into the city.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 2, 'module', true, 'Emergency Contacts', '## 112 — the only number you must memorise

**112** is the single emergency number for Lithuania and the whole EU. It covers police, ambulance and fire.

- Free from any phone, including a phone with no credit and no SIM
- Works 24 hours
- Operators speak English
- Call it for any sudden threat to life, health, safety, the environment or property

**Official information:** [Migration Information Centre — what to do in an emergency](https://micenter.lt/en/what-to-do-in-a-case-of-emergency)

## When you call

Stay on the line and be ready to say:

1. **Where you are** — street, building number, city. If you do not know, describe what you can see.
2. **What happened**
3. **How many people are hurt**
4. **Your name and phone number**

> [!IMPORTANT] Do not hang up until the operator tells you to. They may need to give you instructions while help is on the way.

## Other numbers worth saving

| Who | When to contact them |
| --- | --- |
| **112** | Any emergency — police, ambulance, fire |
| Your university''s international office | Enrolment, documents, university emergencies |
| Your dormitory reception or landlord | Water leak, heating failure, lock-out |
| Your embassy or consulate | Lost passport, serious legal trouble |
| AfaqWay Support | Anything you are unsure about |

Your country may not have an embassy in Vilnius; many are covered from Warsaw, Riga or Stockholm. Find yours now, before you need it, and save the number.

## Non-emergencies

For a health problem that is not an emergency, contact your family doctor or a clinic rather than calling 112 — Step 8 explains how. Pharmacies (*vaistinė*) can advise on minor issues and some are open late.

## Checklist

- [ ] 112 saved in my phone
- [ ] University international office saved
- [ ] Landlord or dormitory reception saved
- [ ] My embassy''s details found and saved
- [ ] My own address written down somewhere I can read it aloud', '{"summary":"Who to call, and when.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 3, 'module', true, 'First Week Recommendations', '## Groceries

The main chains are **Maxima**, **IKI**, **Rimi**, **Lidl** and **Norfa**. All have loyalty cards that are free and genuinely reduce prices — get one for whichever is nearest.

Open-air markets (*turgus*) are cheaper for fruit and vegetables. Halal shops exist in Vilnius and Kaunas; ask AfaqWay Support for the nearest one to you.

## Getting around

Walk your route to campus once before your first class, at the same time of day. Then set up your transport card — Step 9 covers student discounts, which are substantial.

## Banking

You do not need a Lithuanian account on day one; your existing card will work. But start the process in your first week, because it takes time and your university and landlord will both eventually want a local IBAN. Step 7 explains it.

## University orientation

Go, even if it is optional and even if you are tired. Orientation is where you meet the people who will answer your questions for the next three years, and where the international office explains things nobody writes down.

## Meet people early

The **Erasmus Student Network (ESN)** runs events in every Lithuanian university city and they are open to all international students, not only Erasmus. Going to one event in your first fortnight makes an enormous difference to how the year feels.

## Local rules worth knowing

- Drinking alcohol in public places is prohibited, and alcohol is not sold in shops after 20:00 (15:00 on Sundays).
- Smoking is banned on balconies of apartment buildings and in most public spaces.
- Jaywalking is fined; use crossings and wait for the green signal.
- Quiet hours apply at night in residential buildings.

## First Week Success Checklist

- [ ] Nearest supermarket and pharmacy found
- [ ] Loyalty card for the nearest supermarket
- [ ] Route to campus walked once
- [ ] University orientation attended
- [ ] Public transport card obtained
- [ ] Bank account application started
- [ ] One social event attended
- [ ] Residence declaration started', '{"summary":"Settling in comfortably over your first seven days.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 4, 'module', true, 'Useful Maps & Apps', 'Install these in your first week. All have English interfaces.

## Getting around

- **Google Maps** — reliable public transport directions in Lithuanian cities, including live bus times.
- **[Trafi](https://www.trafi.com/)** — built in Lithuania. Combines buses, trolleybuses, scooters and taxis in one journey planner, and is what many locals actually use in Vilnius.
- **Bolt** — taxis, e-scooters and food delivery, all in one app.
- **Google Maps offline** — download the map of your city before you arrive, so navigation works before you have a SIM.

## Transport tickets

- **[JUDU](https://judu.lt/en/)** — the official Vilnius public transport app for tickets and timetables.
- **Kaunas** and other cities have their own official ticket apps; your university will tell you which.

## Daily life

- **Wolt** and **Bolt Food** — food delivery, and useful for groceries late at night.
- **Google Translate** — download Lithuanian for offline use. The camera translation is genuinely useful for reading official letters and food labels.
- Your **bank''s app** — once your account exists, this is where Smart-ID lives, and Smart-ID is what logs you into government services.

## Government and health

- **[Sodra](https://www.sodra.lt/en)** — social insurance and health insurance status.
- **[e-Health portal](https://www.esveikata.lt/)** — appointments, prescriptions and medical records.
- **Smart-ID** — the digital identity most Lithuanian services expect. You set it up through your bank.

> [!TIP] Smart-ID is the single most useful thing you can set up after your bank account. It logs you into healthcare, government portals and your bank without a card reader.

## Checklist

- [ ] Google Maps with your city downloaded offline
- [ ] Trafi or your city''s transport app installed
- [ ] Bolt installed
- [ ] Google Translate with Lithuanian downloaded
- [ ] Delivery app installed
- [ ] Smart-ID planned for after your bank account opens', '{"summary":"The applications that make daily life in Lithuania easier.","source":"xlsx"}'::jsonb, 'student');
end loop;
end $s5$;
