-- Stage 5 chunk 04 · Lithuanian SIM / eSIM · generated by scripts/emit-stage5-chunks.mjs — do not hand-edit.

do $s5$
declare v_plan text; v_stage uuid; v_step uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'Arrival in Lithuania' limit 1;
  if v_stage is null then continue; end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Lithuanian SIM / eSIM' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 3, 'Lithuanian SIM / eSIM', 'A Lithuanian mobile number is essential for daily life. Learn how to choose the best provider, activate your SIM, and register your number correctly.', 'published', true, '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 3, description = 'A Lithuanian mobile number is essential for daily life. Learn how to choose the best provider, activate your SIM, and register your number correctly.', status = 'published',
           required = true, rules = '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb
     where id = v_step;
  end if;

  /* Same tag the full migration uses. Deleting on a tag the blocks do not
     carry would match nothing, so re-running a chunk would append a second copy
     of every module instead of replacing them. Blocks an administrator added by
     hand carry no source tag and survive, exactly as in the full migration. */
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';

      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 0, 'module', true, 'Choosing the Best Mobile Provider', 'Lithuania has three network operators — **Telia**, **Tele2** and **Bitė** — and each sells a cheaper prepaid brand on the same network.

| Prepaid brand | Network | Notes |
| --- | --- | --- |
| **[Labas](https://www.labas.lt/)** | Bitė | Popular with students, self-service through the *Mano Labas* app |
| **[Pildyk](https://pildyk.lt/)** | Tele2 | Consistently among the cheapest bundles; offers eSIM |
| **[Ežys](https://ezys.lt/)** | Telia | Simple plans on Telia''s network; offers eSIM |
| Telia / Tele2 / Bitė contracts | — | Monthly contracts, usually need a Lithuanian bank account and TRP |

## What actually differs

- **Coverage** — all three cover the cities well. Bitė is generally strongest for speed in Vilnius and Kaunas; Tele2 usually wins on price.
- **Price** — the prepaid brands are much cheaper than contracts and need no credit check.
- **eSIM** — available on Ežys and Pildyk, useful if your phone supports it and you want to keep your home number active on the same device.
- **EU roaming** — included on Lithuanian plans, so your number works across the EU at no extra cost.

## Our recommendation for a new student

Start with **prepaid** — Labas, Pildyk or Ežys. You need no bank account, no contract and no credit history, and you can switch later once you are settled and know which network works best where you live.

**[Labas](https://www.labas.lt/)** is a reasonable default: widely available, well known among students, and managed through the *Mano Labas* self-service app.

> [!TIP] Do not sign a 24-month contract in your first week. Prepaid costs a little more per month but commits you to nothing while you are still working out where you will live.

## Checklist

- [ ] Checked whether my phone is unlocked
- [ ] Checked whether my phone supports eSIM
- [ ] Chosen a prepaid brand to start with
- [ ] Decided how much mobile data I actually need', '{"summary":"How the Lithuanian market works and which operator suits a new international student.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 1, 'module', true, 'Registration Requirements', '## Registration is mandatory

Since **1 January 2025**, every prepaid SIM card in Lithuania must be registered to an identified person. This followed an amendment to the Electronic Communications Law. An unregistered card will not activate.

## What to bring

- **Your passport** — this is the document used for registration
- **Your TRP**, if you already have it — useful, though a passport is normally what is required
- A method of payment

## Where to register

- **In the shop** — the assistant registers the card while you wait. This is the simplest route and what we recommend for your first SIM.
- **Online** — some operators allow self-registration through their website or app after purchase. This can be harder with a non-Lithuanian document and no Smart-ID yet.

## Where to buy

- Operator shops in any shopping centre
- Supermarkets — Maxima, IKI, Rimi
- *Narvesen* and *Lietuvos spauda* kiosks
- Vilnius Airport, in Arrivals

> [!MISTAKE] Buying a SIM from an informal seller or accepting a "pre-registered" card from someone else. A number registered in another person''s name can be cut off, and you cannot use it to verify a bank account or a government service.

## Checklist

- [ ] Passport with me when buying
- [ ] SIM registered at the point of sale
- [ ] Registration confirmed before leaving the shop
- [ ] Number saved and sent to family', '{"summary":"What you must bring, and why buying a SIM now requires ID.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 2, 'module', true, 'SIM Activation', '## Activating your card

1. Turn the phone off and insert the SIM, or scan the eSIM QR code.
2. Turn the phone on and enter the **PIN** printed on the card holder.
3. Wait for the network name to appear — this can take a few minutes.
4. Top up if the card did not come with credit.
5. Call or message someone to confirm it works both ways.

Keep the plastic card holder. It carries your **PUK** code, which is the only way to unlock the SIM if the PIN is entered wrongly three times.

## Getting mobile internet working

Data usually configures itself. If it does not:

- Check that **mobile data** is switched on
- Check that **data roaming** is off while you are in Lithuania
- Restart the phone
- If it still fails, ask the operator to send the **APN settings** by SMS

## Topping up

- The operator''s own app — *Mano Labas*, *Pildyk*, *Ežys*
- Supermarket checkouts and kiosks
- Online with a card
- ATMs of the major banks

## Troubleshooting

| Problem | Usual cause |
| --- | --- |
| No network at all | SIM not registered, or the phone is locked to a foreign operator |
| "Emergency calls only" | Registration incomplete — go back to the shop with your passport |
| Calls work, internet does not | APN settings, or no data left in the bundle |
| SIM blocked | Wrong PIN three times — use the PUK from the card holder |

> [!WARNING] If you enter the PUK wrongly ten times the SIM is permanently dead and you have to buy a new one. If you are unsure, stop and go to the operator''s shop.

## Checklist

- [ ] SIM inserted and network showing
- [ ] PUK code stored somewhere safe
- [ ] Test call made and received
- [ ] Mobile data working
- [ ] Top-up method set up', '{"summary":"Getting the card working, and what to do when it does not.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 3, 'module', true, 'Choosing a Monthly Plan', '## What the bundles contain

Lithuanian prepaid bundles are usually monthly and combine minutes, SMS and data. Because your accommodation will have Wi-Fi and your university certainly will, most students need less mobile data than they expect.

| If you | Look for |
| --- | --- |
| Use Wi-Fi at home and on campus | A small bundle, a few GB |
| Navigate and stream on the move | A mid bundle, 20-50 GB |
| Tether your laptop regularly | Unlimited data |
| Call family abroad often | A bundle with international minutes, or use WhatsApp over data |

## Calling home

Do not pay for international minutes by default. WhatsApp, Telegram and similar apps work over data and cost nothing extra. Buy international minutes only if you need to reach a landline.

## EU roaming

Lithuanian plans include roaming across the EU under "roam like at home" rules, so your bundle works when you travel in Europe. Check the fair-use limit for data if you plan a long trip.

## Advice on budget

Start with the smallest bundle that covers a week, watch your actual usage for a month in the operator''s app, then move up or down. Guessing high wastes money every month.

> [!TIP] Set a data warning in your phone''s settings on the day you activate the SIM. It is much easier than discovering the bundle is gone on the 20th.

## Checklist

- [ ] Chosen a starting bundle
- [ ] Auto top-up or a monthly reminder set
- [ ] Data warning configured on the phone
- [ ] Family calling set up over WhatsApp rather than paid minutes
- [ ] Usage reviewed after the first month', '{"summary":"Matching a bundle to how you actually use your phone.","source":"xlsx"}'::jsonb, 'student');
end loop;
end $s5$;
