-- Stage 5 chunk 05 · University Enrollment · generated by scripts/emit-stage5-chunks.mjs — do not hand-edit.

do $s5$
declare v_plan text; v_stage uuid; v_step uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'Arrival in Lithuania' limit 1;
  if v_stage is null then continue; end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'University Enrollment' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 4, 'University Enrollment', 'Complete your university enrollment and activate all academic services.', 'published', true, '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 4, description = 'Complete your university enrollment and activate all academic services.', status = 'published',
           required = true, rules = '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb
     where id = v_step;
  end if;

  /* Same tag the full migration uses. Deleting on a tag the blocks do not
     carry would match nothing, so re-running a chunk would append a second copy
     of every module instead of replacing them. Blocks an administrator added by
     hand carry no source tag and survive, exactly as in the full migration. */
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';

      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 0, 'module', true, 'Enrollment Process', 'Every Lithuanian university runs this slightly differently, but the shape is the same everywhere. Your international office is the authority — this is the map.

## The roadmap

1. **Contact the international office** before or immediately after you arrive, and ask when to come in.
2. **Book an arrival appointment**, if your university uses appointments. Many do in September.
3. **Bring your original documents** — the same ones you submitted during your application, not copies.
4. **Identity verification** — passport and TRP checked against your file.
5. **Sign the study agreement**, if you have not already signed it electronically.
6. **Confirm tuition payment status** with the finance office.
7. **Receive your student ID** and your student number.
8. **Activate your university account** — email, student portal, Wi-Fi.
9. **Collect your timetable** and confirm your study group.

> [!IMPORTANT] Do not leave enrolment until the week classes start. September is the busiest period of the year for every international office in the country, and some steps have queues.

## If something is missing

Missing or incorrect documents are common and almost always fixable. Tell the international office immediately rather than waiting — and tell AfaqWay Support at the same time, so we can help you get a replacement or a translation.', '{"summary":"The route from arriving in the city to being a formally enrolled student.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 1, 'module', true, 'University Checklist', 'Universities differ. Items marked *(varies)* are required by some Lithuanian universities and not others — always confirm with your own international office.

## Documents and identity

- **Submit original documents** — diploma, transcript, passport, TRP. Universal.
- **Certified translations** *(varies)* — required where your originals are not in English or Lithuanian.
- **Photograph for your student ID** *(varies)* — some take it on the spot, some want one in advance.

## Accounts and access

- **Student ID card** — universal. This is also your library card and often your building access.
- **University email address** — universal, and it becomes the official channel for everything. Check it.
- **Student portal account** — universal. Grades, registration, certificates.
- **Moodle or equivalent** *(varies by system)* — where course materials and assignments live.
- **Campus Wi-Fi / eduroam** — universal. Set it up while you are on campus and someone can help.
- **Building access activation** *(varies)* — dormitories and some faculties.

## Money and status

- **Confirm tuition payment** — universal. Ask for written confirmation your balance is clear.
- **Student status certificate** — request one immediately. You will need it for your bank, your transport discount and sometimes your residence declaration.

## Academic

- **Timetable access** — universal.
- **Study group assignment** *(varies)* — common on programmes with seminar groups.
- **Elective / optional course registration** *(varies)* — often has an early deadline. Ask.

## Enrollment Checklist

- [ ] Original documents submitted
- [ ] Identity verified
- [ ] Student ID collected
- [ ] University email working
- [ ] Student portal password set
- [ ] Moodle or learning platform accessible
- [ ] Campus Wi-Fi connected
- [ ] Tuition status confirmed in writing
- [ ] **Student status certificate obtained**
- [ ] Timetable found
- [ ] Elective registration deadline checked', '{"summary":"Every enrolment task, with a note on which are universal and which vary.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 2, 'module', true, 'Required Documents', '## The documents

**Passport** — proves your identity and your right to be in the country. Must be valid; a passport expiring during the academic year causes problems with both the university and the Migration Department.

**Temporary Residence Permit (TRP)** — proves your legal status. Take the physical card, not a photograph of it.

**Original diploma and transcript** — the university must see the originals it admitted you on. They may photocopy and return them, or hold them briefly.

**Certified translations** — where your documents are not in English or Lithuanian. The translation must be done by a certified translator; a translation you did yourself is not accepted.

**Legalisation or apostille** — you completed this in Stage 1. Bring the apostilled versions, not only the plain originals.

**Acceptance letter and study agreement** — your proof of admission and its terms.

**Photograph** — passport-style, for your student ID, where the university does not take one on site.

**Proof of tuition payment** — a bank confirmation or receipt.

## Common mistakes

> [!MISTAKE] Bringing photocopies instead of originals. This is the single most common reason a student is sent away and asked to come back.

- Leaving originals in your home country because you were worried about losing them
- A translation that does not include the translator''s certification
- A name spelled differently across documents — passport, diploma and acceptance letter must match
- An apostille attached to the translation rather than the original, or the other way round, depending on what your university asked for
- Assuming a document accepted for your visa is automatically accepted by the university

## Verification notes

Keep a **digital copy of everything** in cloud storage before you hand anything over, and note the date you submitted each document and who took it. If a document goes missing, that record is what resolves it.

## Checklist

- [ ] All originals physically with me
- [ ] Certified translations included
- [ ] Apostilles attached correctly
- [ ] Names match across every document
- [ ] Digital copies stored in the cloud
- [ ] Record kept of what I submitted and when', '{"summary":"What universities ask for, why, and the mistakes that cause delays.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 3, 'module', true, 'University Resources', '## The international office

Your first stop for anything about documents, status, visas or enrolment. They deal with these questions daily and will know your situation better than a general enquiry desk.

## The library

More than books: study spaces, computers, printing, and access to academic databases you would otherwise pay for. Your student ID is your library card.

## The student portal

Where grades, course registration, certificates and your academic record live. Learn to download a **student status certificate** yourself — you will need one repeatedly, and self-service is faster than asking.

## Moodle or your learning platform

Course materials, assignment submission and deadlines. Turn on notifications; missed deadlines in the first semester are almost always missed announcements.

## Academic support

Most universities offer writing help, language support and study skills workshops, usually free and usually under-used. If academic English is hard for you, this is the cheapest fix available.

## Career centre

Part-time jobs, internships and CV help. Step 11 covers the job search itself, but the career centre is where the university-vetted opportunities are.

## Student union

Represents students, runs events, and is the right place to go if you have a problem with a course or a grade and do not know the process.

## Finding your own university''s links

Search your university''s site for "international students", or ask the international office for their student handbook. Every Lithuanian university publishes one, usually in English, and it answers most of these questions in one document.

National information for international students: **[Study in Lithuania](https://studyin.lt/)**

## Checklist

- [ ] International office location and email saved
- [ ] Library visited and card working
- [ ] Student portal bookmarked
- [ ] Learning platform notifications on
- [ ] Student handbook downloaded
- [ ] Career centre location noted
- [ ] Student union channel followed', '{"summary":"The services you are already paying for and should start using.","source":"xlsx"}'::jsonb, 'student');
end loop;
end $s5$;
