-- Stage 5 chunk 06 · Residence Registration · generated by scripts/emit-stage5-chunks.mjs — do not hand-edit.

do $s5$
declare v_plan text; v_stage uuid; v_step uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'Arrival in Lithuania' limit 1;
  if v_stage is null then continue; end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Residence Registration' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 5, 'Residence Registration', 'After settling into your accommodation, you may need to register your place of residence depending on your municipality and university requirements. This step explains the complete process and helps you understand what is required.', 'published', true, '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 5, description = 'After settling into your accommodation, you may need to register your place of residence depending on your municipality and university requirements. This step explains the complete process and helps you understand what is required.', status = 'published',
           required = true, rules = '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb
     where id = v_step;
  end if;

  /* Same tag the full migration uses. Deleting on a tag the blocks do not
     carry would match nothing, so re-running a chunk would append a second copy
     of every module instead of replacing them. Blocks an administrator added by
     hand carry no source tag and survive, exactly as in the full migration. */
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';

      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 0, 'module', true, 'Understanding Residence Registration', '## What it is

Declaring your place of residence (*gyvenamosios vietos deklaravimas*) tells the Lithuanian state the address where you actually live. It is a civil registration, not an immigration application, and it is separate from your TRP.

Your declared address is what the state, your municipality and many services use to reach you.

## Why it matters to you

- It is a **legal obligation** for residents of Lithuania, including foreign students.
- Banks, clinics and municipal services may ask for it.
- Some student discounts and municipal services are tied to a declared address.
- Failing to declare can result in **administrative liability**.

## When you declare it

You have a choice, and this is the part most students get wrong:

1. **When applying for your residence permit** — if you indicated your Lithuanian address in your residence permit application, the address is recorded then and **you do not need to declare separately**.
2. **After collecting your TRP** — declare at your local **eldership** (*seniūnija*) or the Migration Department, normally **within one month**.

> [!IMPORTANT] Check which of these applies to you before queuing anywhere. If you gave an address in your MIGRIS application, you may already be declared. If you are not sure, ask AfaqWay Support or the Migration Department.

## The space requirement

Foreign nationals coming to Lithuania for studies must have a living space of **at least 4 square metres** per person at the declared address. A landlord or dormitory that cannot meet this cannot host your declaration.

## Official sources

- [Migration Department — declaring your place of residence](https://www.migracija.lt/en/-/foreigners-can-also-declare-their-place-of-residence-at-the-migration-department)
- [Migration Department (Ministry of the Interior)](https://migracija.lrv.lt/en/)

## Checklist

- [ ] Checked whether I already declared an address in my MIGRIS application
- [ ] Confirmed the one-month deadline from collecting my TRP, if it applies
- [ ] Confirmed my accommodation meets the 4 m² requirement
- [ ] Confirmed my landlord or dormitory will consent', '{"summary":"What declaring your place of residence means, and when you have to do it.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 1, 'module', true, 'Municipality Registration Process', '## The roadmap

1. **Find your eldership** (*seniūnija*). Each municipality is divided into elderships, and you go to the one covering your address. Your municipality''s website lists them.
2. **Check whether an appointment is needed.** Larger cities generally use booking systems; some elderships accept walk-ins.
3. **Bring the landlord, or bring their consent.** The property owner normally has to consent to your declaration — either in person, or with a written, signed consent form.
4. **Submit the declaration** with your documents.
5. **Receive confirmation.** Ask for a printed or electronic confirmation and keep it.

## Online options

Lithuania has strong e-government, and declaration can often be completed electronically through the national portal — but this generally requires **Smart-ID or a qualified electronic signature**, which you will only have after your bank account exists. For most new students the in-person route is faster on arrival.

You can also declare at the **Migration Department** rather than the eldership.

## Processing time

The declaration itself is usually completed during the visit. Delays come from appointments and from landlord consent, not from the processing.

## Common mistakes

> [!MISTAKE] Arriving without the property owner or their written consent. This is the most common reason students are turned away and have to book a second appointment.

- Going to the wrong eldership for your address
- Bringing a rental contract that does not name you
- Assuming a dormitory has already declared you — ask reception explicitly
- Leaving it past the one-month deadline

## Checklist

- [ ] Correct eldership identified
- [ ] Appointment booked, if required
- [ ] Landlord attending, or written consent obtained
- [ ] Documents gathered
- [ ] Confirmation received and saved', '{"summary":"How the declaration actually works, step by step.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 2, 'module', true, 'Required Documents', '## What you may be asked for

**Passport** — proves your identity. Always required.

**Temporary Residence Permit (TRP)** — proves you are legally resident and entitled to declare an address. Bring the card.

**Rental agreement** — proves you have a right to live at the address you are declaring. It must name you as the tenant.

**Owner''s consent** — the property owner agreeing to your declaration at their address. Either the owner attends in person with their ID, or provides a signed consent form.

**Dormitory confirmation** — if you live in university accommodation, a letter from the university or dormitory administration replaces the rental agreement and owner consent.

**University confirmation / student status certificate** — not always required for the declaration itself, but useful to have and often requested alongside.

**Completed declaration form** — provided at the eldership, or downloadable from your municipality''s website.

## Why each is required

The declaration links a *person* to an *address*. So the officer needs to establish three things: that you are who you say you are (passport), that you may legally reside in Lithuania (TRP), and that you have a genuine right to that specific address (contract plus owner consent, or dormitory confirmation).

## Verification notes

Take **originals and one photocopy of each**. Bring your landlord''s phone number in case a question comes up that only they can answer. Photograph the completed form before you hand it in.

## Checklist

- [ ] Passport
- [ ] TRP card
- [ ] Rental agreement naming me, or dormitory confirmation
- [ ] Owner present or written consent signed
- [ ] Photocopies of everything
- [ ] Landlord reachable by phone during the appointment', '{"summary":"What to bring, and why each item is asked for.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 3, 'module', true, 'City-Specific Information', 'Procedures are set nationally, but the office you visit and the booking system are local. Start with your own municipality.

## Vilnius

Vilnius publishes a dedicated English page for foreign nationals declaring residence, including which documents to bring and how to book.

- [Vilnius municipality — declaration of foreign nationals'' place of residence](https://vilnius.lt/savivaldybe/deklaravimas/declaration-of-foreign-nationals-place-of-residence-in-vilnius)
- [Go Vilnius — practical information for newcomers](https://www.govilnius.lt/)

## Kaunas, Klaipėda, Šiauliai, Panevėžys and elsewhere

Search your municipality''s own site for *deklaravimas* (declaration) or ask your university''s international office, which handles this every September and will know the local office and its habits.

## If you are not sure which city applies

It is the municipality of the address where you **actually live**, not where you study, if the two differ.

## A national fallback

The **Migration Department** accepts declarations regardless of municipality, which is useful if your local eldership has no appointments.

- [Migration Department](https://www.migracija.lt/en)
- [Migration Information Centre — practical guides in English](https://micenter.lt/en/declaration-of-residence)

## Checklist

- [ ] My municipality''s declaration page found
- [ ] The correct office and its address noted
- [ ] Booking method understood
- [ ] Opening hours checked', '{"summary":"Where to start in the main Lithuanian student cities.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 4, 'module', true, 'Practical Advice', '## Start early

The one-month clock, where it applies, runs from collecting your TRP — not from when you find an apartment. If you are still in temporary accommodation, tell AfaqWay Support so we can help you plan.

## Landlord reluctance

Some landlords hesitate to allow a declaration. It is worth knowing:

- Declaration does not give you ownership rights.
- It does not prevent the landlord from ending the tenancy under the contract.
- Agree it **before you sign** the rental contract, and get it in writing. A landlord who refuses is a reason to keep looking.

> [!WARNING] Never declare an address you do not actually live at, and never accept an offer to "register" you at an address for a fee. A false declaration is a legal problem for you, not for the person selling it.

## What to expect on the day

- Bring everything on the document list, plus photocopies.
- Not every officer speaks fluent English. Google Translate on your phone is genuinely useful, and so is asking a Lithuanian-speaking friend to come.
- The visit itself is usually short.

## Keep the confirmation

Save the confirmation digitally and on paper. Banks, clinics and the university may all ask for it, and getting a duplicate is slower than keeping the original.

## Where to ask for help

- Your university''s international office
- [Migration Information Centre](https://micenter.lt/en) — free advice for foreigners in Lithuania
- AfaqWay Support

## Residence Registration Checklist

- [ ] Established whether I already declared during my MIGRIS application
- [ ] Landlord consent agreed in writing
- [ ] Correct office identified and appointment booked
- [ ] Passport, TRP, contract and consent gathered
- [ ] Declaration submitted
- [ ] Confirmation saved digitally and on paper
- [ ] Deadline met', '{"summary":"Avoiding the delays that catch students out.","source":"xlsx"}'::jsonb, 'student');
end loop;
end $s5$;
