-- Stage 5 chunk 07 · Banking · generated by scripts/emit-stage5-chunks.mjs — do not hand-edit.

do $s5$
declare v_plan text; v_stage uuid; v_step uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'Arrival in Lithuania' limit 1;
  if v_stage is null then continue; end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Banking' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 6, 'Banking', 'Opening a local bank account will make it easier to receive payments, pay rent, manage daily expenses, and access many university and government services.', 'published', true, '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 6, description = 'Opening a local bank account will make it easier to receive payments, pay rent, manage daily expenses, and access many university and government services.', status = 'published',
           required = true, rules = '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb
     where id = v_step;
  end if;

  /* Same tag the full migration uses. Deleting on a tag the blocks do not
     carry would match nothing, so re-running a chunk would append a second copy
     of every module instead of replacing them. Blocks an administrator added by
     hand carry no source tag and survive, exactly as in the full migration. */
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';

      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 0, 'module', true, 'Why You Need a Lithuanian Bank Account', 'You can survive on a foreign card for a few weeks. You cannot run your life here on one.

## What needs a local account

- **Rent** — most landlords expect a transfer from a Lithuanian account, and some will not accept anything else.
- **Tuition instalments** — paying from abroad each time means transfer fees and delays.
- **A salary** — if you take a part-time job, your employer will need a Lithuanian IBAN.
- **Utility bills and your phone contract** — direct debits need a local account.
- **Smart-ID** — the digital identity that logs you into government services, healthcare and your university is set up through a Lithuanian bank. This is the quiet reason a local account matters most.

## What it saves you

- No foreign transaction fees on daily spending
- No poor exchange rate on every coffee
- Instant SEPA transfers within the EU
- Student discounts some banks offer on account fees

> [!TIP] Open the account early even if you do not need it yet. The process takes time, and Smart-ID depends on it.

## Checklist

- [ ] Understood why a local account matters
- [ ] Decided roughly when to open it
- [ ] Kept my foreign card as a backup', '{"summary":"What a local IBAN unlocks that a foreign card does not.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 1, 'module', true, 'Choosing the Best Student Bank', '## The traditional banks

**[Swedbank](https://www.swedbank.lt/)** — the largest retail bank in Lithuania, with the widest branch and ATM network. Runs a youth programme for customers under 22, which can mean reduced fees. Good English support online.

**[SEB](https://www.seb.lt/en)** — large, well-established, strong mobile app, English interface.

**[Luminor](https://www.luminor.lt/en)** — present across the Baltics. Allows remote account opening for non-citizens who already have a qualified Smart-ID or mobile signature; without those you visit a branch.

**Šiaulių bankas** — smaller Lithuanian bank, sometimes more flexible with newcomers, but a smaller branch network and less English-language support online.

## The fintech option

**Revolut** — a licensed Lithuanian institution, so a Revolut account carries a Lithuanian IBAN. Opening is fast and entirely in-app, and it is excellent for spending and currency exchange.

> [!WARNING] Do not rely on a fintech account alone. Some landlords, employers and institutions still expect a traditional bank, and Smart-ID generally comes through a traditional bank. Many students use Revolut for daily spending and a traditional bank for everything official.

## Comparison

| | Branch network | English support | Remote opening | Smart-ID | Best for |
| --- | --- | --- | --- | --- | --- |
| Swedbank | Largest | Good | Usually in branch | Yes | Most students |
| SEB | Large | Good | Usually in branch | Yes | Strong app |
| Luminor | Medium | Good | With Smart-ID | Yes | Baltic-wide |
| Šiaulių bankas | Smaller | Limited | In branch | Yes | Flexibility |
| Revolut | None | Excellent | Fully in-app | No | Daily spending |

## Our recommendation

Open a **traditional bank account** — Swedbank or SEB are the safest defaults for a new international student — and add **Revolut** alongside it if you travel or send money home.

## Checklist

- [ ] Chosen a main bank
- [ ] Checked whether it has a student or youth account
- [ ] Located the nearest branch
- [ ] Decided whether to add a fintech account', '{"summary":"How the main options compare for an international student.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 2, 'module', true, 'Opening Your Account', '## The roadmap

1. **Book an appointment.** Walk-ins are often refused. Book online or by phone, and ask for an English-speaking adviser.
2. **Gather your documents** — see below.
3. **Attend the appointment.** Expect 30-60 minutes and questions about why you need the account.
4. **Sign the agreement.**
5. **Receive your IBAN** — usually the same day.
6. **Set up online banking** before you leave the branch.
7. **Receive your debit card** — normally posted within about a week, or collected from the branch.
8. **Activate the card** at an ATM with its PIN.
9. **Set up Smart-ID** once your account is active.

## What to bring

- **Passport** — always required.
- **Temporary Residence Permit** — or a certificate from the Migration Department confirming your right to reside.
- **Student status certificate** from your university — this is the document that explains *why* you need a Lithuanian account, and it is the one students most often forget.
- **Proof of address** — rental contract or dormitory confirmation.
- **Your Lithuanian phone number** — needed for verification.
- Sometimes: a document showing your **country of tax residence**.

> [!MISTAKE] Arriving without a student status certificate. Banks must document why a non-resident needs an account, and "I am studying here" is not enough without proof. Get the certificate during enrolment (Step 5).

## If you are refused

It happens, and it is usually about missing documentation rather than about you. Ask exactly which document is missing, get it, and rebook — or try another bank. Tell AfaqWay Support and we will help.

## Checklist

- [ ] Appointment booked
- [ ] Passport, TRP, student certificate and proof of address gathered
- [ ] Lithuanian phone number active
- [ ] Account opened and IBAN received
- [ ] Online banking working
- [ ] Card received and activated
- [ ] Smart-ID set up', '{"summary":"The route from booking an appointment to a working card.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 3, 'module', true, 'Online Banking', '## Mobile banking

Every major Lithuanian bank has a good mobile app in English. Install it at the branch while someone can help you log in for the first time.

## Smart-ID

**Smart-ID** is the digital identity most Lithuanian services expect. Once set up through your bank, it logs you into:

- Your bank
- Government and municipal e-services
- The [e-Health portal](https://www.esveikata.lt/)
- Many university systems

You approve each login by entering a PIN on your phone. Set it up as soon as your account is open — it removes friction from almost everything else in this stage.

## Transfers

- **Within Lithuania and the EU** — SEPA transfers, usually instant or same-day, and typically free or very cheap.
- **Outside the EU** — slower and more expensive. For sending money home, compare your bank against Revolut or Wise before assuming the bank is best.

To make a transfer you need the recipient''s **IBAN** and name. Always check the IBAN twice; a transfer to a wrong-but-valid IBAN is very hard to recover.

## Cards and payments

- Contactless is accepted almost everywhere, including on buses.
- **Apple Pay** and **Google Pay** are supported by the major Lithuanian banks.
- Freeze and unfreeze your card from the app if you misplace it — faster than calling.

## Security

> [!IMPORTANT] No bank will ever ask for your Smart-ID PIN, your password or a code by phone, email or WhatsApp. Anyone who does is stealing from you. Approve a Smart-ID request only when you started the action yourself.

- Turn on transaction notifications
- Never approve a login you did not initiate
- Use the official app, not a link from a message

## Checklist

- [ ] Mobile banking app installed and working
- [ ] Smart-ID set up and tested
- [ ] Transaction notifications on
- [ ] Apple Pay or Google Pay added
- [ ] Card freeze feature located in the app', '{"summary":"Day-to-day digital banking in Lithuania.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 4, 'module', true, 'Financial Tips', '## Separate your money

Keep two pots: one for **fixed costs** (rent, bills, phone) and one for **spending**. Move the fixed amount aside on the day money arrives. Most banking apps support a savings space or second account for exactly this.

## Avoid the common fees

- **Foreign currency** — spending on a home-country card in Lithuania costs you on every purchase. Move to your local card.
- **ATM withdrawals** — use your own bank''s ATMs; other networks charge.
- **Airport exchange** — the worst rate you will find. Withdraw from an ATM instead.
- **Monthly account fees** — ask about a student or youth account.

## Sending money home

Compare your bank against Revolut and Wise. Look at the **total** cost — fee plus exchange margin — not the headline fee.

## Build a small buffer

Aim for one month of rent set aside. It turns a broken laptop or an unexpected trip from a crisis into an inconvenience.

> [!MISTAKE] Keeping everything in one account and judging your budget by the balance. The balance always looks fine until rent day.

## Student Banking Checklist

- [ ] Lithuanian account open and card working
- [ ] Smart-ID active
- [ ] Fixed costs separated from spending money
- [ ] Rent standing order or reminder set
- [ ] Cheapest route for sending money home identified
- [ ] Emergency buffer started
- [ ] Account fees checked and a student account requested', '{"summary":"Keeping control of your money as a student.","source":"xlsx"}'::jsonb, 'student');
end loop;
end $s5$;
