-- Stage 5 chunk 08 · Healthcare · generated by scripts/emit-stage5-chunks.mjs — do not hand-edit.

do $s5$
declare v_plan text; v_stage uuid; v_step uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'Arrival in Lithuania' limit 1;
  if v_stage is null then continue; end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Healthcare' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 7, 'Healthcare', 'Understanding the healthcare system will help you receive medical assistance quickly and confidently whenever you need it.', 'published', true, '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 7, description = 'Understanding the healthcare system will help you receive medical assistance quickly and confidently whenever you need it.', status = 'published',
           required = true, rules = '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb
     where id = v_step;
  end if;

  /* Same tag the full migration uses. Deleting on a tag the blocks do not
     carry would match nothing, so re-running a chunk would append a second copy
     of every module instead of replacing them. Blocks an administrator added by
     hand carry no source tag and survive, exactly as in the full migration. */
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';

      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 0, 'module', true, 'Understanding Healthcare in Lithuania', 'Lithuania has a public healthcare system funded through compulsory health insurance, alongside a private sector.

## Public healthcare

Funded through **compulsory health insurance** (*privalomasis sveikatos draudimas*, **PSD**), administered by **[Sodra](https://www.sodra.lt/en)**. If you are covered, it pays for:

- Your family doctor (GP)
- Specialist appointments, with a referral
- Hospital treatment
- Prescription medicines at a reduced price

Public care is inexpensive once you are insured, but waiting times for non-urgent specialists can be long.

## Private healthcare

Pay-per-visit clinics. More expensive, but you can usually be seen within days, often in English, and without a referral. Many international students use private clinics for minor issues and the public system for anything serious.

## The family doctor is the front door

Lithuanian healthcare is built around the **family doctor** (*šeimos gydytojas*). For anything that is not an emergency, you see them first, and they refer you onward if needed. You cannot normally book a public specialist directly.

## Emergency care

**112** for emergencies. Emergency treatment is provided regardless of insurance status — never delay calling because you are unsure about cover.

## Official sources

- [Sodra — compulsory health insurance](https://www.sodra.lt/en)
- [Migration Information Centre — healthcare system](https://micenter.lt/en/healthcare-system)

## Checklist

- [ ] Understood the difference between public and private care
- [ ] Understood that the family doctor comes first
- [ ] Saved 112', '{"summary":"How the system is organised, and where you fit into it.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 1, 'module', true, 'Health Insurance', '## You already have insurance

You bought health insurance for your TRP application in Stage 3 — valid for at least two years with minimum coverage of €30,000. **Keep the certificate.** It is your proof of cover and you may be asked for it.

## How PSD works

**PSD** is Lithuania''s compulsory health insurance and it is what gives access to the public system.

- **If you work in Lithuania** — contributions are deducted automatically from your salary, and you become covered.
- **If you do not work** — you are not automatically covered by PSD, and you rely on your private policy, or you pay PSD contributions yourself. Self-paid PSD is tied to the national minimum wage and was in the region of €80 per month during 2026.

> [!IMPORTANT] This is the point most students misunderstand. Holding a TRP does not by itself make you publicly insured. Check your status on the Sodra portal once you have Smart-ID, and ask AfaqWay Support if you are unsure.

## If you take a part-time job

Your employer registers you with Sodra and PSD contributions start automatically. Once insured you can register with a family doctor and use the public system.

## What your private policy covers

Read your own certificate. Policies differ on dental care, chronic conditions, pregnancy and repatriation. Know what is excluded *before* you need it.

## Official source

- [Sodra — self-paid compulsory health insurance contributions](https://sodra.lt/imokos/savarankiskai-moku-privalomojo-sveikatos-draudimo-psd-imokas?lang=en)

## Checklist

- [ ] Insurance certificate saved digitally and on paper
- [ ] Policy read, exclusions understood
- [ ] PSD status checked on Sodra
- [ ] Renewal date noted in my calendar', '{"summary":"What cover you have, and what you may need to arrange.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 2, 'module', true, 'Registering with a Clinic', '## Choosing a clinic

Pick a clinic (*poliklinika*) near where you live that has a contract with your territorial health insurance fund. Your university''s international office will usually recommend one used to international students.

## How to register

1. Go to the clinic with your **passport**, **TRP** and **insurance details**.
2. Complete the registration form (*prašymas*) choosing a family doctor.
3. You are attached to that doctor from then on.
4. You may change clinic later, though switching too often can incur a fee.

## Booking appointments

- **By phone** — the standard route, though English is not guaranteed.
- **Online** — through the [e-Health portal](https://www.esveikata.lt/) or your clinic''s own system, usually needing Smart-ID.
- **In person** — at the registration desk.

For non-urgent matters expect to book days ahead. Ask for the first available English-speaking doctor when you book.

## Private clinics

If you need to be seen quickly or want a guaranteed English-speaking doctor, private clinics take direct bookings and often have appointments within a day or two. You pay per visit.

## Prescriptions

Prescriptions are electronic. Your doctor issues one to the national system and you collect it at any pharmacy (*vaistinė*) with your ID.

## Checklist

- [ ] Clinic near home identified
- [ ] Registered with a family doctor
- [ ] Booking method understood
- [ ] Nearest pharmacy located
- [ ] e-Health portal access set up', '{"summary":"Choosing a family doctor and booking your first appointment.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 3, 'module', true, 'Medical Emergencies', '## Call 112

**112** is free, works from any phone with or without a SIM, and operators speak English. Call it for:

- Loss of consciousness, difficulty breathing, chest pain
- Serious injury or heavy bleeding
- Suspected stroke — face drooping, arm weakness, speech difficulty
- Severe allergic reaction
- Any situation where someone''s life may be at risk

Give **your location first**, then what happened. Stay on the line.

## Hospital emergency departments

Go directly to a hospital emergency department for urgent problems that are not life-threatening — a bad fracture, a deep cut, a high fever that will not come down. You do not need a referral.

Bring your passport, TRP and insurance certificate if you can, but **never delay treatment to fetch documents**.

## Urgent but not an emergency

- Your **family doctor** — same-day slots often exist for urgent cases.
- A **private clinic** — fastest route to an English-speaking doctor.
- A **pharmacy** — pharmacists in Lithuania are well trained and can advise on minor problems and over-the-counter treatment.

## Pharmacies

*Vaistinė*. Widely available, and larger cities have late-night and 24-hour ones. Many medicines that need a prescription elsewhere also need one here.

## Mental health

Moving countries is genuinely hard, and struggling with it is common rather than shameful. Most Lithuanian universities offer free psychological support to students — ask your international office or student union. If you are in crisis, call 112.

## Checklist

- [ ] 112 saved and understood
- [ ] Nearest hospital emergency department located
- [ ] Nearest 24-hour pharmacy located
- [ ] Insurance certificate on my phone
- [ ] University psychological support contact found', '{"summary":"What to do when it is urgent.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 4, 'module', true, 'Useful Healthcare Resources', '## Official portals

- **[Sodra](https://www.sodra.lt/en)** — health insurance status, contributions, and your social insurance record. Check here to confirm whether you are covered by PSD.
- **[e-Health (esveikata.lt)](https://www.esveikata.lt/)** — appointments, electronic prescriptions and your medical records in one place. Needs Smart-ID.
- **[Migration Information Centre](https://micenter.lt/en/healthcare-system)** — plain-English explanations of the healthcare system for foreigners, run as a public information service.

## On your phone

- Your **clinic''s app or booking page**
- **e-Health**, once Smart-ID is set up
- **Google Translate** with Lithuanian downloaded — useful for medicine packaging and instructions
- Your **insurance provider''s** contact details and policy number

## Words worth knowing

| Lithuanian | English |
| --- | --- |
| *Vaistinė* | Pharmacy |
| *Poliklinika* | Clinic |
| *Šeimos gydytojas* | Family doctor |
| *Greitoji pagalba* | Ambulance |
| *Skubi pagalba* | Emergency department |
| *Receptas* | Prescription |

## Healthcare Checklist

- [ ] Insurance certificate stored digitally
- [ ] PSD status checked on Sodra
- [ ] Registered with a family doctor
- [ ] e-Health access working
- [ ] Nearest pharmacy and emergency department known
- [ ] 112 saved
- [ ] University psychological support contact saved', '{"summary":"The official services and tools worth having.","source":"xlsx"}'::jsonb, 'student');
end loop;
end $s5$;
