-- Stage 5 chunk 09 · Public Transport · generated by scripts/emit-stage5-chunks.mjs — do not hand-edit.

do $s5$
declare v_plan text; v_stage uuid; v_step uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'Arrival in Lithuania' limit 1;
  if v_stage is null then continue; end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Public Transport' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 8, 'Public Transport', 'Public transportation is the easiest and most affordable way to travel around Lithuania. This step explains everything you need to start using buses, trolleybuses, and other local transportation services.', 'published', true, '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 8, description = 'Public transportation is the easiest and most affordable way to travel around Lithuania. This step explains everything you need to start using buses, trolleybuses, and other local transportation services.', status = 'published',
           required = true, rules = '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb
     where id = v_step;
  end if;

  /* Same tag the full migration uses. Deleting on a tag the blocks do not
     carry would match nothing, so re-running a chunk would append a second copy
     of every module instead of replacing them. Blocks an administrator added by
     hand carry no source tag and survive, exactly as in the full migration. */
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';

      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 0, 'module', true, 'Understanding Public Transport', 'Public transport in Lithuania is cheap, punctual and easy to use once you have a card.

## In the cities

- **Buses** — everywhere, and the backbone of every city network.
- **Trolleybuses** — electric buses on overhead wires, in Vilnius and Kaunas. Same tickets, same cards.
- **Kaunas funicular** — two historic funicular railways, more charming than practical.

Vilnius transport is run by **[JUDU](https://judu.lt/en/)**, which is also the name of the app and the card.

## Between cities

- **Intercity buses** — the most common way to travel between Lithuanian cities. Frequent, comfortable and inexpensive. Book at [autobusubilietai.lt](https://autobusubilietai.lt/).
- **Trains** — [LTG Link](https://ltglink.lt/en) runs the passenger network. Often more comfortable than buses on the routes it serves.

Both offer student discounts with the right card.

## How you pay

You validate every journey. There is no conductor and no gate — you tap your card or your bank card on the validator when you board, and inspectors check at random.

> [!WARNING] Always validate, on every leg of every journey, even when the bus is empty and even if you have a monthly pass. Travelling without a validated ticket is treated as fare evasion and fined.

## Checklist

- [ ] Identified which company runs transport in my city
- [ ] Understood that I must validate on every boarding
- [ ] Found the routes between home and campus', '{"summary":"How buses, trolleybuses and trains work in Lithuanian cities.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 1, 'module', true, 'Transport Cards', '## What to get

In **Vilnius**, the **[JUDU](https://judu.lt/en/)** card (also called the *Vilniečio kortelė*). Other cities have their own equivalent.

## Where to buy

- *Narvesen* and *Lietuvos spauda* kiosks
- Customer service centres
- Vilnius Airport, in Arrivals — useful on your first day
- Supermarkets in some cities

The card itself costs a small one-off fee.

## Registering it

Register the card online or in the app and link it to your name. Two reasons this matters:

1. A registered card can be **blocked and replaced** with its balance if you lose it.
2. Your **student discount can only be attached to a registered card**.

## Loading it

- The operator''s app
- Kiosks and customer service points
- Online with a bank card
- Ticket machines

You can load either a **single-journey balance** or a **period pass** (month, term, or a set number of days).

## Using a bank card instead

In Vilnius you can tap a contactless bank card directly on the validator for a single ticket, around €1. Convenient for a visitor — but it does **not** carry your student discount, so it is not what you want day to day.

> [!TIP] Buy the card in your first week and register it immediately, even before your student status is confirmed. You can attach the discount later without buying a new card.

## Checklist

- [ ] Transport card bought
- [ ] Card registered in my name
- [ ] Balance or period pass loaded
- [ ] Top-up method saved', '{"summary":"Getting the card, loading it and using it.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 2, 'module', true, 'Transport Applications', '## Ticketing

- **[JUDU](https://judu.lt/en/)** — official Vilnius transport app. Buy tickets, top up your card, check timetables, plan journeys.
- Your own city''s official app, if you are not in Vilnius. Ask your international office.

## Journey planning

- **[Trafi](https://www.trafi.com/)** — built in Lithuania and what many locals use. Combines buses, trolleybuses, e-scooters and taxis into a single plan, with live arrival times.
- **Google Maps** — reliable public transport directions with live departures in Lithuanian cities. The easiest starting point.

## Intercity

- **[Autobusų bilietai](https://autobusubilietai.lt/)** — intercity bus tickets across Lithuania.
- **[LTG Link](https://ltglink.lt/en)** — train tickets and timetables.

## Micromobility

- **Bolt** — e-scooters and taxis in one app.
- Seasonal city bike schemes operate in the larger cities in summer.

## Why each matters

Google Maps answers *"how do I get there"*. Trafi answers *"what is the fastest way right now"*. JUDU answers *"how do I pay"*. Most students end up with all three.

## Checklist

- [ ] Official ticket app installed
- [ ] Trafi or Google Maps set up for my city
- [ ] Intercity booking site bookmarked
- [ ] Home and campus saved as favourite locations', '{"summary":"The apps that make journeys easy.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 3, 'module', true, 'Student Discounts', 'Student transport discounts in Lithuania are among the best in Europe, and many international students never claim them.

## The two cards

**[LSP — Lithuanian Student Identity Card](https://lsp.lt/en)** (*Lietuvos studento pažymėjimas*)

- Around **80% off city public transport**
- Around **50% off intercity** travel
- Issued to students at Lithuanian institutions
- Can integrate a Vilnius or Kaunas transport e-ticket into the same card

**[ISIC Lithuania](https://www.isic.lt/en/)** — the international student card

- Around **50% off public transport**
- Also gives discounts in shops, cinemas and museums, and works abroad
- Can also carry an integrated Vilnius or Kaunas e-ticket

> [!TIP] If you are choosing purely on transport cost, the **LSP** discount is larger. Many students hold both: LSP for transport, ISIC for international and retail discounts.

## Eligibility

- You must be a **full-time** student. Part-time students are generally not eligible for transport concessions.
- Your student status must be active and verifiable.

## How to get one

1. Enrol and confirm your student status (Step 5).
2. Apply through [lsp.lt](https://lsp.lt/en) or [isic.lt](https://www.isic.lt/en/order-isic/), or through your university — many issue them centrally.
3. Provide your student number and a photograph.
4. Collect the card, or receive the virtual version.
5. **Attach the discount to your transport card** — this is the step people forget, and without it you keep paying full price.

## Validity

The discount follows your student status and must be renewed each academic year. Set a reminder.

## Checklist

- [ ] Confirmed I am registered as full-time
- [ ] Applied for LSP, ISIC, or both
- [ ] Card received
- [ ] **Discount attached to my transport card and tested on a journey**
- [ ] Renewal reminder set for next academic year', '{"summary":"The discount is large — make sure you actually claim it.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 4, 'module', true, 'Travel Tips', '## Peak hours

Roughly 07:30-09:00 and 16:30-18:30 on weekdays. Buses on university routes get full. Leave earlier for anything that matters.

## Ticket inspections

Inspectors board at random, in plain clothes, and will ask to see a validated ticket and — if you travelled at a student rate — your **student card**.

> [!MISTAKE] Travelling on a student fare without carrying the student card. The discount is not valid without the card that proves it, and the fine applies exactly as if you had no ticket.

## Winter

Buses run through the winter and are heated. Stops are not. Use the live arrival times in the app rather than standing outside guessing — this is the single best reason to install Trafi.

## Night travel

City services thin out late in the evening. Check the last departure before a night out, or budget for a Bolt home.

## Weekends and holidays

Reduced timetables. Check the app rather than assuming the weekday schedule.

## Safety

Lithuanian public transport is safe, including at night. Ordinary precautions are enough: keep your phone in a pocket rather than your hand near the door, and keep your bag closed on a crowded bus.

## Public Transport Checklist

- [ ] Transport card bought and registered
- [ ] Student discount applied and tested
- [ ] Ticket app installed
- [ ] Journey planner installed
- [ ] Home-to-campus route known, with a backup
- [ ] Student card carried whenever I travel
- [ ] Last departure times checked for my route', '{"summary":"Travelling confidently and avoiding fines.","source":"xlsx"}'::jsonb, 'student');
end loop;
end $s5$;
