-- Stage 5 chunk 10 · Financial Setup · generated by scripts/emit-stage5-chunks.mjs — do not hand-edit.

do $s5$
declare v_plan text; v_stage uuid; v_step uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'Arrival in Lithuania' limit 1;
  if v_stage is null then continue; end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Financial Setup' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 9, 'Financial Setup', 'Managing your finances correctly is one of the most important skills for a successful student life. This step will help you create a realistic budget, understand your monthly expenses, and discover useful student discounts.', 'published', true, '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 9, description = 'Managing your finances correctly is one of the most important skills for a successful student life. This step will help you create a realistic budget, understand your monthly expenses, and discover useful student discounts.', status = 'published',
           required = true, rules = '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb
     where id = v_step;
  end if;

  /* Same tag the full migration uses. Deleting on a tag the blocks do not
     carry would match nothing, so re-running a chunk would append a second copy
     of every module instead of replacing them. Blocks an administrator added by
     hand carry no source tag and survive, exactly as in the full migration. */
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';

      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 0, 'module', true, 'Understanding Student Living Costs', 'Lithuania is one of the more affordable EU countries to study in, but costs have risen. These are indicative ranges for **2026**; Vilnius is the most expensive city, Kaunas, Klaipėda and Šiauliai are cheaper.

## Typical monthly costs

| Category | Typical range | Notes |
| --- | --- | --- |
| Accommodation | €150-450 | Dormitory at the low end, private studio at the high end |
| Utilities | €40-120 | Much higher in winter if heating is not included |
| Food (cooking at home) | €150-250 | Eating out regularly pushes this well up |
| Public transport | €5-25 | With the student discount |
| Mobile phone | €5-15 | Prepaid bundle |
| Home internet | €10-20 | Often included in dormitories |
| Study materials | €10-30 | Averaged across the year |
| Personal and social | €50-150 | Entirely up to you |

## Average Monthly Student Budget

| Living style | Realistic monthly total |
| --- | --- |
| Careful — dormitory, cooking at home | **€400-550** |
| Comfortable — shared flat, some eating out | **€600-800** |
| Private apartment in central Vilnius | **€900+** |

> [!IMPORTANT] These are living costs only. Tuition, insurance and travel home are separate and should be planned annually, not monthly.

## Costs students forget

- Winter clothing in your first year — a proper coat and boots are not optional here
- Heating in January and February
- Document fees, translations and card renewals
- Flights home at the end of the year
- The deposit on a new apartment if you move

## Checklist

- [ ] Estimated my own monthly total from the table
- [ ] Added winter costs to the plan
- [ ] Confirmed whether my rent includes heating
- [ ] Separated annual costs from monthly ones', '{"summary":"What a month in Lithuania actually costs a student.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 1, 'module', true, 'Creating Your Monthly Budget', '## The method

Split every euro into three:

1. **Fixed** — rent, utilities, phone, transport pass, insurance. Same every month.
2. **Variable** — food, study materials, social life. You control these.
3. **Savings** — even €20 a month builds a buffer.

## A worked example

A student with €650 a month:

| | Amount |
| --- | --- |
| Dormitory rent | €200 |
| Utilities | €50 |
| Phone | €10 |
| Transport (with student discount) | €15 |
| **Fixed total** | **€275** |
| Groceries | €200 |
| Personal and social | €100 |
| **Variable total** | **€300** |
| **Savings** | **€75** |

The discipline is in the order. On the day money arrives, move the fixed total and the savings out of your spending account. What is left is genuinely yours to spend, and you cannot accidentally spend the rent.

## Setting goals

- **Month 1** — build a €100 emergency buffer
- **Month 3** — one month''s rent saved
- **Year 1** — enough for a flight home plus a deposit

## Reviewing it

Look at your actual spending once a month, in your banking app. The first review is always a surprise. Adjust the plan to reality rather than pretending the plan was right.

## Checklist

- [ ] Listed my fixed costs
- [ ] Set a realistic variable budget
- [ ] Chosen a savings amount, however small
- [ ] Set up a separate space or account for fixed costs
- [ ] Put a monthly review in my calendar', '{"summary":"A simple budget that survives contact with real life.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 2, 'module', true, 'Saving Money as a Student', '## The big three

**1. Cook at home.** The single largest lever. Cooking most meals instead of eating out typically saves €150-250 a month.

**2. Claim your transport discount.** Up to 80% off city travel with an LSP card (Step 9). Students who never register the discount pay several times more all year.

**3. Get the right accommodation.** A dormitory place versus a private studio can be a €250 monthly difference.

## Groceries

- **Loyalty cards** — Maxima, IKI, Rimi, Lidl. Free, and prices genuinely differ with and without them.
- **Lidl and Norfa** are usually cheapest for a weekly shop.
- **Markets** (*turgus*) beat supermarkets on fruit and vegetables.
- Shop with a list, after eating, once a week.

## Student discounts beyond transport

Your **ISIC** card and often your university ID get you reduced prices at:

- Museums and galleries
- Cinemas and theatres
- Some restaurants and cafés
- Software and online services — many offer large student discounts on an academic email

## Free through your university

- Library books, databases and printing quotas
- Sports facilities and gyms
- Language courses, including Lithuanian
- Academic writing and study skills support
- Psychological support

These are paid for by your tuition. Not using them is leaving money behind.

## Small habits

- Refill a water bottle rather than buying
- Buy the second-hand textbook, or borrow it
- Use student-priced software licences

## Checklist

- [ ] Loyalty cards for my nearest supermarkets
- [ ] Cooking most meals at home
- [ ] Transport discount active
- [ ] ISIC or LSP card in my wallet
- [ ] University free services identified', '{"summary":"Where the savings actually are.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 3, 'module', true, 'Useful Financial Applications', '## Start with your bank

Every major Lithuanian banking app categorises your spending automatically and shows where the money went. For most students this is enough, and it needs no setup.

- Turn on **transaction notifications**
- Use **savings spaces** or a second account to separate fixed costs
- Check the **monthly spending summary**

## Multi-currency and sending money home

- **Revolut** — spending analytics, savings vaults, currency exchange at good rates. A Lithuanian IBAN.
- **Wise** — usually the cheapest way to send money to a non-EU country. Compare before every large transfer.

## Budgeting apps

If your bank''s app is not enough, general budgeting tools that let you set category limits and track manually are widely available. Choose one that lets you **enter cash spending manually** — cash is where budgets leak.

> [!WARNING] Never connect an app to your bank account unless it is your bank''s own app or a regulated provider you have checked. Some "free" budgeting apps make money from your data, and some are outright fraudulent. If in doubt, track manually.

## What matters more than the app

Reviewing your spending once a month. A simple spreadsheet you actually look at beats a sophisticated app you installed and forgot.

## Checklist

- [ ] Bank app notifications on
- [ ] Spending categories reviewed once
- [ ] Method chosen for sending money home
- [ ] A monthly review reminder set', '{"summary":"Tools that make tracking money easy rather than a chore.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 4, 'module', true, 'Financial Checklist', 'Work through this during your first month. It takes an hour in total and prevents most money problems students run into.

## Accounts and payments

- [ ] Lithuanian bank account open, card working
- [ ] Smart-ID active
- [ ] Rent standing order or a monthly reminder set
- [ ] Cheapest route for sending money home identified

## Budget

- [ ] Monthly income written down
- [ ] Fixed costs listed and totalled
- [ ] Variable budget set
- [ ] Savings amount chosen
- [ ] Fixed money kept separate from spending money

## Discounts

- [ ] LSP or ISIC card obtained
- [ ] Transport discount attached and tested
- [ ] Supermarket loyalty cards
- [ ] University free services identified

## Safety net

- [ ] Emergency buffer started
- [ ] Insurance renewal date in my calendar
- [ ] Annual costs — flights, tuition, renewals — planned separately

## Habit

- [ ] Monthly spending review in my calendar
- [ ] Transaction notifications on

> [!TIP] If you only do three things: separate rent from spending money, cook at home, and claim your transport discount. Those three cover most of the gap between a tight month and a comfortable one.', '{"summary":"Everything to have in place by the end of your first month.","source":"xlsx"}'::jsonb, 'student');
end loop;
end $s5$;
