-- Stage 5 chunk 11 · Find a Job (Optional) · generated by scripts/emit-stage5-chunks.mjs — do not hand-edit.

do $s5$
declare v_plan text; v_stage uuid; v_step uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'Arrival in Lithuania' limit 1;
  if v_stage is null then continue; end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Find a Job (Optional)' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 10, 'Find a Job (Optional)', 'If you would like to earn extra income while studying, this step explains how to prepare for the Lithuanian job market and where to find trusted opportunities. This step is optional and you may skip it.', 'published', false, '{"documents":[],"source":"xlsx","allowSkip":true,"completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 10, description = 'If you would like to earn extra income while studying, this step explains how to prepare for the Lithuanian job market and where to find trusted opportunities. This step is optional and you may skip it.', status = 'published',
           required = false, rules = '{"documents":[],"source":"xlsx","allowSkip":true,"completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb
     where id = v_step;
  end if;

  /* Same tag the full migration uses. Deleting on a tag the blocks do not
     carry would match nothing, so re-running a chunk would append a second copy
     of every module instead of replacing them. Blocks an administrator added by
     hand carry no source tag and survive, exactly as in the full migration. */
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';

      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 0, 'module', true, 'Working While Studying', '## You may work

Your **Temporary Residence Permit for studies gives you the right to work**. You do not need a separate work permit — this is one of the genuine advantages of studying in Lithuania compared with many other countries.

## The hour limits

| Who | During the academic year | During official holidays |
| --- | --- | --- |
| Non-EU **bachelor''s** students | up to **20 hours per week** | full-time, up to 40 hours |
| Non-EU master''s and PhD students | generally full-time | full-time |
| EU / EEA / Swiss students | no limit | no limit |

As a bachelor''s student on a TRP, plan around **20 hours a week** in term time.

> [!IMPORTANT] These limits are conditions of your residence permit. Exceeding them puts your permit at risk, which is a far bigger problem than the extra income is worth. Keep your contracted hours within the limit and keep your payslips.

## What your employer must do

A legitimate employer will:

- Give you a **written employment contract** before you start
- Register you with **Sodra**, which also starts your health insurance
- Pay into a **bank account**, not in cash
- Deduct taxes and contributions from your salary

> [!WARNING] Undeclared work — cash in hand, no contract — is illegal, leaves you with no rights if you are not paid, gives you no health insurance, and can affect your residence permit. Do not accept it, however convenient it looks.

## Official sources

- [Study in Lithuania — working in Lithuania](https://studyin.lt/about-lithuania/work-in-lithuania/)
- [Employment Service of Lithuania](https://uzt.lt/en/)
- [Migration Department](https://www.migracija.lt/en)

Rules change. Confirm the current limits with your international office or the Migration Department before signing a contract.

## Checklist

- [ ] Confirmed my weekly hour limit
- [ ] Understood I need a written contract
- [ ] Understood the employer must register me with Sodra
- [ ] Bank account ready to receive a salary', '{"summary":"Your right to work on a student residence permit, and its limits.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 1, 'module', true, 'Preparing Your CV', '## What a Lithuanian CV looks like

- **One to two pages**, no more
- Reverse chronological — most recent first
- **In English** for international companies, Lithuanian for local ones
- A photograph is common in Lithuania, though never required
- Clean and plain: no elaborate graphics

## What to include

1. **Contact details** — name, Lithuanian phone number, professional email, city
2. **Short profile** — two or three lines on who you are and what you are looking for
3. **Education** — your current degree, university, expected graduation
4. **Experience** — any work, including part-time, volunteering and university projects
5. **Skills** — languages with levels, software, technical skills
6. **Languages** — state your English level honestly; note any Lithuanian, even basic

## With little experience

This is the normal position for a first-year student, and employers hiring students know it.

- Lead with **education and skills** rather than experience
- Include **university projects** and describe what you actually did
- Include **volunteering** — it counts
- List **languages** prominently; multilingual students are genuinely valuable here
- Name concrete things: "served 50+ customers a day in a busy café" beats "good communication skills"

## Free tools

- Your university''s **career centre** — free CV reviews, and the most useful option
- **Europass** ([europass.europa.eu](https://europass.europa.eu/en)) — the free EU standard CV builder, recognised everywhere in Europe
- **LinkedIn** — keep it consistent with your CV; recruiters check

## Where to look for work

- **[CVbankas.lt](https://en.cvbankas.lt/)** — the most visited job portal in Lithuania
- **CV.lt**, **CVonline.lt**, **CVmarket.lt** — other established general portals
- **[LinkedIn Jobs](https://www.linkedin.com/jobs/)** — strongest for international companies and internships
- **[Employment Service (Užimtumo tarnyba)](https://uzt.lt/en/)** — the official state employment service
- Your **university career centre and career days**

## Checklist

- [ ] CV written, one to two pages
- [ ] Reviewed by the university career centre
- [ ] Language levels stated honestly
- [ ] LinkedIn profile matching my CV
- [ ] Accounts created on CVbankas and one other portal', '{"summary":"A CV that works in the Lithuanian market, with little experience.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 2, 'module', true, 'Finding Job Opportunities', '## Jobs students realistically get

- **Hospitality** — cafés, restaurants, hotels
- **Retail** — supermarkets and shops
- **Delivery** — Bolt Food, Wolt
- **Customer support** — international companies in Vilnius hire for language skills, and this is where being multilingual pays
- **IT and tech internships** — Vilnius has a large tech and fintech sector
- **On-campus work** — library, labs, student services
- **Tutoring** — your own language, or a subject you are strong in

> [!TIP] If you speak Arabic, French or another language alongside English, look at the international business services companies in Vilnius. They pay better than hospitality and actively want language skills.

## Your university first

Before the public portals:

- The **career centre** — vetted employers used to student schedules
- **Career days** — most Lithuanian universities run them, and international students are welcome
- **Department noticeboards and mailing lists** — research assistant and lab roles are often advertised nowhere else

## Applying safely

- Apply through the **company''s own site or an established portal**
- Research the employer before an interview
- Meet in a **public place or the company''s office**
- Never pay a fee to get a job — legitimate employers and agencies never charge candidates
- Never hand over your passport; showing it is normal, surrendering it is not
- Be cautious about "agents" who promise a job for a fee

> [!WARNING] If an offer arrives without an interview, promises unusually high pay for simple work, or asks you to receive and forward money, it is a scam. Some of these involve money laundering, which is a criminal matter for you as well as for them.

## Balancing work and study

You came here to get a degree. Twenty hours a week is a real commitment on top of a full course load — start with fewer hours, see how the first month goes, and increase only if your studies hold up.

## Checklist

- [ ] University career centre visited
- [ ] Profiles created on the main portals
- [ ] Job alerts set up
- [ ] Employers researched before applying
- [ ] Decided a realistic weekly hour target', '{"summary":"Where student jobs actually are, and how to apply safely.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 3, 'module', true, 'Interview Preparation', '## What to expect

Interviews for student jobs are usually short and practical. For hospitality and retail, expect a single conversation with a manager. For office roles, expect two rounds and possibly a task.

## Common questions

- Tell me about yourself
- Why do you want this job?
- What is your availability? *(Be exact — days and hours. Bring your timetable.)*
- How long do you plan to stay in Lithuania?
- Do you have the right to work here? *(Yes — your TRP for studies gives it, up to 20 hours a week in term time.)*
- Describe a time you handled a difficult situation
- What is your English level? Do you speak any Lithuanian?

## How to prepare

1. Research the company — 10 minutes on their website is enough and it shows.
2. Prepare **three concrete examples** from study, work or volunteering.
3. Know your **timetable** precisely; availability is often the deciding factor for a student role.
4. Prepare two questions to ask them — about the team, the schedule, or training.
5. Practise out loud in English at least once.

## Practical details

- **Dress** — smart casual for hospitality and retail; business casual for an office. Clean and tidy matters more than expensive.
- **Arrive 10 minutes early.** Punctuality is taken seriously in Lithuania.
- **Bring** a printed CV, your passport or TRP, and your student certificate.
- **Online interviews** — test camera and microphone beforehand, sit somewhere quiet with a plain background.

## During the interview

- Greet with a handshake and eye contact
- Be honest about your experience — enthusiasm and reliability are what student employers want
- Be clear about your hour limit; a good employer respects it
- Ask when you will hear back

## Checklist

- [ ] Company researched
- [ ] Three examples prepared
- [ ] Timetable and exact availability known
- [ ] Two questions ready
- [ ] Outfit decided
- [ ] Documents ready
- [ ] Practised out loud once', '{"summary":"Getting through your first interview in Lithuania.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 4, 'module', true, 'Taxes and Employment Basics', '> [!IMPORTANT] This module is a plain-English introduction, not tax advice. Rates and thresholds change every year. Confirm anything that affects your money with [Sodra](https://www.sodra.lt/en), the [State Tax Inspectorate (VMI)](https://www.vmi.lt/) or your employer''s HR department.

## Your employment contract

Read it before signing. It should state your job title, hours, salary, start date, holiday entitlement and notice period. You are entitled to a copy — keep it.

## Gross and net pay

Lithuanian salaries are usually advertised **gross** (*bruto*), before deductions. What reaches your account is **net** (*neto*), and the difference is significant.

Deducted from your gross salary:

- **Personal income tax (GPM)**
- **Social insurance contributions**, including your **compulsory health insurance (PSD)**

> [!TIP] Always ask whether a quoted salary is gross or net. Confusing the two is the most common mistake students make in Lithuanian salary negotiations.

## Why the deductions are good news

Your PSD contribution is what enrols you in the **public healthcare system** (Step 8). Once employed and registered with Sodra, you can register with a family doctor and use public healthcare.

## What your employer does

- Registers you with Sodra **before** your first working day
- Deducts and pays your taxes
- Gives you payslips

You generally do not have to file anything yourself for ordinary employment income — but check your situation, especially if you have income from more than one source or from abroad.

## Holiday and rights

Employees in Lithuania are entitled to paid annual leave, and the Labour Code protects part-time workers as well as full-time ones. Your working time limit as a student is a condition of your permit, not of the Labour Code.

## Official sources

- [Sodra](https://www.sodra.lt/en) — social and health insurance
- [State Tax Inspectorate (VMI)](https://www.vmi.lt/) — income tax
- [Employment Service](https://uzt.lt/en/) — jobseeker rights and support

## Checklist

- [ ] Contract read before signing, copy kept
- [ ] Confirmed whether the salary quoted is gross or net
- [ ] Confirmed my employer registers me with Sodra
- [ ] Payslips saved
- [ ] Working hours within my permit limit
- [ ] Checked my insurance status on Sodra after the first month', '{"summary":"An introduction only — the official sources are authoritative.","source":"xlsx"}'::jsonb, 'student');
end loop;
end $s5$;
