-- Stage 5 chunk 12 · Social Integration · generated by scripts/emit-stage5-chunks.mjs — do not hand-edit.

do $s5$
declare v_plan text; v_stage uuid; v_step uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'Arrival in Lithuania' limit 1;
  if v_stage is null then continue; end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Social Integration' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 11, 'Social Integration', 'Studying abroad is more than attending classes. This step helps you build friendships, adapt to Lithuanian culture, and enjoy university life.', 'published', true, '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 11, description = 'Studying abroad is more than attending classes. This step helps you build friendships, adapt to Lithuanian culture, and enjoy university life.', status = 'published',
           required = true, rules = '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb
     where id = v_step;
  end if;

  /* Same tag the full migration uses. Deleting on a tag the blocks do not
     carry would match nothing, so re-running a chunk would append a second copy
     of every module instead of replacing them. Blocks an administrator added by
     hand carry no source tag and survive, exactly as in the full migration. */
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';

      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 0, 'module', true, 'Everyday Life in Lithuania', 'Lithuanians are often described as reserved. It is worth understanding this correctly: it is politeness, not coldness. People are quieter with strangers and genuinely warm once they know you.

## Everyday etiquette

- **Greetings** — *Labas* (hello) or *Laba diena* (good day). A handshake is normal in formal settings.
- **Punctuality matters.** Being late without warning is read as inconsiderate, at university and at work.
- **Take your shoes off** when entering someone''s home. Always.
- **Quiet in public.** Loud conversation on buses stands out.
- **Queue properly** and let people off before boarding.
- **Personal space** is a little larger than in southern Europe or the Middle East.

## In the classroom

- Professors are addressed formally unless invited otherwise.
- Deadlines are firm. An extension needs a genuine reason and an early request.
- Questions are welcome, but there is less spontaneous debate than in some cultures. Silence after a question is normal, not hostility.

## Rules to know

- **No alcohol in public places.** Shops stop selling at 20:00, and at 15:00 on Sundays.
- **Smoking** is banned in most public spaces, including apartment balconies.
- **Jaywalking is fined.** Wait for the green signal even on an empty street — locals do.
- **Quiet hours** at night in residential buildings.

## Religion and diversity

Lithuania is predominantly Catholic and religious practice is treated as private. There are mosques and Muslim communities in Vilnius and Kaunas, and halal food is available in the larger cities. Ask AfaqWay Support for what is near you.

## Weather, honestly

Winter is long, cold and dark, with sunset in mid-afternoon in December. This affects mood, and it affects most newcomers in their first year. Invest in a proper coat and waterproof boots early, get outside in daylight when you can, and consider vitamin D. If the darkness starts weighing on you, that is common — talk to your university''s psychological support.

## Checklist

- [ ] Learned *Labas* and *Ačiū*
- [ ] Understood the alcohol and smoking rules
- [ ] Bought proper winter clothing
- [ ] Understood that reserve is not unfriendliness', '{"summary":"Local customs and everyday etiquette, so you feel at ease quickly.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 1, 'module', true, 'Student Communities', 'The students who settle well are almost always the ones who joined something in their first month. This is the highest-return item in the whole stage.

## ESN — Erasmus Student Network

**[ESN](https://esn.lt/)** has sections at every major Lithuanian university. Despite the name, events are generally open to **all international students**, not only Erasmus exchange students.

They run city tours, trips around Lithuania and the Baltics, language cafés, parties and buddy programmes.

> [!TIP] Many ESN sections run a **buddy or mentor programme** pairing you with a local student. If yours does, sign up. It is the single fastest way to understand how things actually work here.

## Your student union

Every Lithuanian university has one. They represent students, run events, and are who to ask when you have a problem with a course or a grade and do not know the process.

## Clubs and societies

Sports teams, debate, music, photography, volunteering, faculty societies. Most are free or nearly free and welcome beginners.

## National and cultural associations

Student associations for particular nationalities and regions exist in most university cities — a good source of practical advice from people who arrived a year or two before you.

## Volunteering

A genuine way to meet Lithuanians rather than only other internationals, to practise the language, and to build something for your CV.

## Why it matters

Beyond friendship: your classmates are who you revise with, who tells you an assignment brief changed, and who notices when you have not been seen for a week. Loneliness in the first winter is the most common reason international students struggle, and it is much easier to prevent than to fix.

## Checklist

- [ ] Found my university''s ESN section
- [ ] Joined the international students group chat
- [ ] Signed up for a buddy programme if one exists
- [ ] Attended one social event in my first month
- [ ] Joined one club or society', '{"summary":"Where to meet people, and why it matters more than it sounds.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 2, 'module', true, 'Learning Basic Lithuanian', 'Lithuanian is one of the oldest living Indo-European languages, and it is genuinely difficult. Nobody expects you to be fluent. But a small effort is noticed and appreciated far more than you might expect.

## Absolute essentials

| Lithuanian | English |
| --- | --- |
| *Labas* | Hello (informal) |
| *Laba diena* | Good day (formal) |
| *Ačiū* | Thank you |
| *Prašau* | Please / you''re welcome |
| *Atsiprašau* | Sorry / excuse me |
| *Taip* / *Ne* | Yes / No |
| *Viso gero* | Goodbye |
| *Ar kalbate angliškai?* | Do you speak English? |
| *Nesuprantu* | I don''t understand |

## Shopping

| Lithuanian | English |
| --- | --- |
| *Kiek kainuoja?* | How much does it cost? |
| *Kur yra...?* | Where is...? |
| *Sąskaitą, prašau* | The bill, please |
| *Maišelis* | Bag |
| *Nuolaida* | Discount |

## Transport

| Lithuanian | English |
| --- | --- |
| *Autobusas* / *Troleibusas* | Bus / Trolleybus |
| *Stotelė* | Stop |
| *Bilietas* | Ticket |
| *Traukinys* | Train |
| *Oro uostas* | Airport |

## Emergencies

| Lithuanian | English |
| --- | --- |
| *Padėkite!* | Help! |
| *Man reikia gydytojo* | I need a doctor |
| *Iškvieskite greitąją* | Call an ambulance |
| *Vaistinė* | Pharmacy |
| *Policija* | Police |

## Where to learn

- **Your university** — most offer free or subsidised Lithuanian courses to international students. This is the best option and it is usually already paid for by your tuition.
- **[Duolingo](https://www.duolingo.com/)** — has a Lithuanian course; good for vocabulary and daily habit.
- **ESN language cafés** — informal practice with native speakers.
- **Google Translate** — download Lithuanian for offline use; the camera mode reads official letters and food labels.

## Realistic goal

Aim for greetings, numbers, and being able to order coffee by the end of your first semester. That is enough to change how daily interactions feel.

## Checklist

- [ ] Learned the ten essential phrases
- [ ] Checked whether my university offers free Lithuanian classes
- [ ] Downloaded Lithuanian for offline translation
- [ ] Used *Labas* and *Ačiū* at least once today', '{"summary":"You do not need fluency. A hundred words changes daily life.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 3, 'module', true, 'Useful Applications', '## Getting around

- **Google Maps** — navigation and live public transport
- **[Trafi](https://www.trafi.com/)** — Lithuanian-built multimodal journey planner
- **Bolt** — taxis and e-scooters

## Food

- **Wolt** and **Bolt Food** — restaurant and grocery delivery
- Supermarket apps — **Maxima**, **Rimi**, **IKI**, **Lidl** — for loyalty pricing and offers

## Money

- Your **bank''s app**
- **Smart-ID** — your digital identity for banking, government and healthcare
- **Revolut** or **Wise** — currency exchange and sending money home

## Everyday services

- **[e-Health](https://www.esveikata.lt/)** — appointments and prescriptions
- **[Sodra](https://www.sodra.lt/en)** — insurance status
- Your **transport app** — JUDU in Vilnius
- Your **university''s app or portal**

## Buying and selling

- **[Skelbiu.lt](https://www.skelbiu.lt/)** — second-hand furniture, bikes and electronics, which is how most students furnish a room affordably
- **Vinted** — founded in Lithuania and used everywhere here for second-hand clothing

## Communication

- **WhatsApp** — how you will reach AfaqWay Support and most international friends
- **Messenger** — widely used by Lithuanian students; many course groups live there
- **Google Translate** — with Lithuanian downloaded

## Culture and events

- **[Go Vilnius](https://www.govilnius.lt/)** — the official city guide: events, museums, what is on
- **[Lithuania Travel](https://lithuania.travel/en)** — the official national tourism site

## Checklist

- [ ] Navigation and transport apps installed
- [ ] Delivery app installed
- [ ] Banking and Smart-ID working
- [ ] Second-hand marketplace installed
- [ ] Course group chats joined
- [ ] City events source bookmarked', '{"summary":"The apps that make everyday life in Lithuania simpler.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 4, 'module', true, 'Exploring Lithuania', 'Lithuania is small, travel within it is cheap, and you can reach most of the country in a few hours. Students who explore it enjoy their degree considerably more.

## In Vilnius

- **Vilnius Old Town** — one of the largest surviving medieval old towns in Europe and a UNESCO World Heritage Site
- **Gediminas Castle Tower** — the view over the city
- **Užupis** — the self-declared "republic" of artists, with its own constitution on a wall in many languages
- **The National Museum of Lithuania** and the **MO Museum** of modern art
- **Vingis** and **Bernardinai** parks

## Elsewhere in the country

- **Trakai** — the island castle on a lake, half an hour from Vilnius, and the classic first day trip
- **Kaunas** — a European Capital of Culture with strong interwar modernist architecture
- **Curonian Spit** — UNESCO-listed sand dunes and forest on the Baltic coast
- **Klaipėda and Palanga** — the seaside, best in summer
- **Hill of Crosses**, near Šiauliai — hundreds of thousands of crosses on one hill
- **Aukštaitija** and **Dzūkija** national parks — lakes and forest

## Beyond Lithuania

Riga is about four hours by bus, Warsaw is reachable overnight, and Tallinn is a little further. Flights from Vilnius across Europe are inexpensive if booked early. Your student status and ISIC card reduce many of these costs.

## How to do it cheaply

- **ESN trips** are organised, subsidised and social — the easiest way to start
- **Intercity buses** are cheap, and cheaper still with a student discount
- **Museums** are often free or reduced for students, and some have free days
- Travel **off-season** for the coast

## Official resources

- [Lithuania Travel](https://lithuania.travel/en) — the national tourism board
- [Go Vilnius](https://www.govilnius.lt/) — the official Vilnius city guide

## Checklist

- [ ] Explored my own city''s old town or centre
- [ ] Visited one museum with my student discount
- [ ] Taken one trip outside my city
- [ ] Joined one ESN trip
- [ ] Made a list of three places to see before I graduate', '{"summary":"The country beyond your campus.","source":"xlsx"}'::jsonb, 'student');
end loop;
end $s5$;
