-- Stage 5 chunk 13 · Academic Success · generated by scripts/emit-stage5-chunks.mjs — do not hand-edit.

do $s5$
declare v_plan text; v_stage uuid; v_step uuid;
begin
foreach v_plan in array array['self_service', 'full_service'] loop
  select id into v_stage from public.journey_stages
   where country = 'LT' and plan = v_plan and title = 'Arrival in Lithuania' limit 1;
  if v_stage is null then continue; end if;

  select id into v_step from public.journey_steps
   where stage_id = v_stage and title = 'Academic Success' limit 1;

  if v_step is null then
    insert into public.journey_steps (stage_id, sort_order, title, description, status, required, rules)
    values (v_stage, 12, 'Academic Success', 'This final learning step provides practical strategies for academic success throughout your university journey.', 'published', true, '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb)
    returning id into v_step;
  else
    update public.journey_steps
       set sort_order = 12, description = 'This final learning step provides practical strategies for academic success throughout your university journey.', status = 'published',
           required = true, rules = '{"documents":[],"source":"xlsx","completion":"self","cta":"Done","unlockedBy":"Congratulations! Welcome to Lithuania 🎉"}'::jsonb
     where id = v_step;
  end if;

  /* Same tag the full migration uses. Deleting on a tag the blocks do not
     carry would match nothing, so re-running a chunk would append a second copy
     of every module instead of replacing them. Blocks an administrator added by
     hand carry no source tag and survive, exactly as in the full migration. */
  delete from public.journey_blocks where step_id = v_step and (data ->> 'source') = 'xlsx';

      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 0, 'module', true, 'Building Effective Study Habits', 'University study is different from school: less supervision, more reading, and results that depend on what you do between classes.

## What works

**Active recall.** Test yourself instead of re-reading. Close the book and write what you remember, then check. This feels harder than re-reading, which is exactly why it works better.

**Spaced repetition.** Review material after a day, then a week, then a month. Spacing the same total study time across days beats cramming it into one.

**Practice under real conditions.** Do past papers with a timer. The skill of answering an exam question is separate from knowing the material.

**Teach it.** Explaining a topic to a classmate exposes what you only half understand.

## What does not work

> [!MISTAKE] Highlighting and re-reading feel productive and are close to useless on their own. Recognising a page is not the same as being able to reproduce its argument in an exam.

Cramming the night before also fails twice: it produces a worse grade *and* nothing you can build on next semester.

## Note-taking

- **Cornell method** — split the page: notes on the right, cue questions on the left, a summary at the bottom. Built for later self-testing.
- **Write in your own words.** Transcribing the lecturer verbatim is typing, not learning.
- **Review notes within 24 hours** — a ten-minute pass makes them usable months later.

## Planning your week

1. Block your fixed commitments — lectures, seminars, work shifts
2. Add study blocks for each subject, ideally the same times each week
3. Protect one full day off
4. Plan the week on Sunday, in ten minutes

## Preparing for exams

- Start **three weeks out**, not three days
- Find out the **format** early — essay, multiple choice, oral — and practise that format
- Prioritise by weighting and by what you are weakest at
- Sleep before the exam. A tired brain loses more marks than an extra hour of revision gains.

## Checklist

- [ ] Chosen a note-taking method
- [ ] Weekly study blocks in my calendar
- [ ] Reviewing notes within 24 hours
- [ ] Testing myself instead of re-reading
- [ ] Exam formats identified for this semester', '{"summary":"Study methods that are actually supported by evidence.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 1, 'module', true, 'Time Management', '## Three horizons

**The semester.** In week one, put every exam and assignment deadline into one calendar. Nearly every "sudden" crisis was visible in the syllabus in September.

**The week.** Plan on Sunday. Fixed commitments first, then study blocks, then social time. Ten minutes.

**The day.** Choose the two or three things that actually matter. A list of fifteen items is a wish, not a plan.

## Making it work

- **Time-block** — decide *when* you will do something, not just that you will
- **Do the hardest thing first**, when you are freshest
- **Work in focused blocks** with real breaks — 45 to 50 minutes is a reasonable unit
- **Batch small tasks** — email, admin, printing — into one slot instead of letting them interrupt study

## If you are working part-time

Twenty hours of work plus a full course load is a real load. Protect study time by putting it in the calendar *before* you agree your shifts, and be honest with your employer about exam periods — a good employer expects this from student staff.

## Prioritising

Ask two questions: **when is it due**, and **how much is it worth**. A 40%-weighted assignment due in two weeks beats a 5% quiz due tomorrow, even though the quiz feels more urgent.

## Beating procrastination

- Start with **five minutes**. Starting is the hard part; continuing is easier.
- Break large tasks into pieces small enough to be obvious.
- Remove the phone from the room. Not face-down — out.
- Study where you do not sleep. Your brain associates places with behaviours.

## Tools

Anything you will actually open: Google Calendar, Notion, Todoist, or paper. The best system is the one you look at daily.

## Checklist

- [ ] All semester deadlines in one calendar
- [ ] Sunday planning slot booked
- [ ] Study blocks protected before agreeing work shifts
- [ ] A place to study that is not my bed
- [ ] One day off per week', '{"summary":"Balancing study, work and a life.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 2, 'module', true, 'University Learning Resources', '## The library

Books, quiet study space, group rooms, printing, and — most valuably — **access to academic databases** you would otherwise pay for. Librarians will show you how to search properly; twenty minutes with one saves hours on every assignment afterwards.

## Academic writing support

Most Lithuanian universities offer writing centres or academic English support. If English is not your first language, this is the highest-value free service available to you, and it is consistently under-used by the students who need it most.

## Office hours

Every lecturer has them. Almost nobody comes. Turning up with a specific question is the single most efficient way to fix a misunderstanding, and lecturers remember the students who do.

## Tutoring and peer support

Many faculties run peer tutoring or mentoring, often with senior students. Free, and less intimidating than asking a professor.

## The learning platform

Moodle or your university''s equivalent holds materials, deadlines and announcements. **Turn on notifications.** Most missed deadlines in first year are missed announcements.

## Online, free

- **[Coursera](https://www.coursera.org/)** and **[edX](https://www.edx.org/)** — university courses, many auditable free
- **[Khan Academy](https://www.khanacademy.org/)** — strong for maths and statistics foundations
- **[MIT OpenCourseWare](https://ocw.mit.edu/)** — full course materials, free
- **Google Scholar** — academic search; link it to your university library for full-text access

## Accessibility and support

If you have a condition affecting your studies, universities have formal support and adjustments. Talk to student services early rather than struggling quietly.

## Checklist

- [ ] Library visited and databases accessed once
- [ ] Writing support located
- [ ] One lecturer''s office hours attended
- [ ] Learning platform notifications on
- [ ] Peer tutoring checked', '{"summary":"What your tuition already pays for.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 3, 'module', true, 'Productivity Tools', '## Notes

- **Notion** — notes, databases and planning in one place; free personal plan, and students often get more
- **OneNote** — free with a university Microsoft account, good for handwriting on a tablet
- **Obsidian** — plain-text notes stored locally, good for linking ideas across a degree
- **Paper** — genuinely fine, and better for recall in lectures

## Calendar

**Google Calendar** or **Outlook**. One calendar, with everything in it. Two calendars means missing whatever is in the other one.

## Tasks

**Todoist**, **Microsoft To Do**, or your notes app. Keep exactly one list.

## Cloud storage

**Google Drive** or **OneDrive**, usually free and generous through your university account.

> [!IMPORTANT] Keep your university work in cloud storage, not only on your laptop. A stolen or broken laptop the week before a deadline is a disaster that costs nothing to prevent.

## Writing and referencing

- **Zotero** — free reference manager. Collects sources and generates your bibliography in the required style. Learn it in first year and it saves you days over a degree.
- **Grammarly** or your word processor''s checker for a final pass
- Your university''s **citation style guide** — ask which style your faculty requires

## Focus

- **Forest** or any focus timer
- Website blockers during study blocks
- Phone in another room

## Do not over-build

Three tools you use beat ten you configured once. Notes, calendar, cloud storage. Add anything else only when you feel the need.

## Checklist

- [ ] One notes app chosen
- [ ] One calendar with everything in it
- [ ] Cloud storage set up and syncing
- [ ] Zotero installed and citation style confirmed
- [ ] University Microsoft or Google account activated', '{"summary":"A small, reliable toolkit.","source":"xlsx"}'::jsonb, 'student');
      insert into public.journey_blocks (step_id, sort_order, kind, enabled, title, body, data, audience)
      values (v_step, 4, 'module', true, 'Long-Term Academic Success', 'You have moved country, arranged a residence permit, found somewhere to live and enrolled at a university in a language that is not your first. Everything after this is smaller than what you have already done.

## Across the degree

**First year** — build habits, pass everything, make friends, get comfortable. Grades matter less than not falling behind.

**Second year** — go deeper. Start looking for internships and think about what you actually enjoy.

**Final year** — thesis, serious job search, and decisions about staying or moving on.

## Build skills, not only grades

Employers look at your degree, then at everything else: languages, part-time work, volunteering, projects, societies. Your multilingualism and the fact that you moved countries at eighteen are genuine advantages — learn to describe them as such.

## Networking, without the awkwardness

- Keep in touch with classmates; they become your professional network
- Go to guest lectures and career days
- Keep LinkedIn current
- Stay in touch with lecturers whose subjects you enjoyed — they write references

## Staying in Lithuania after graduation

Lithuania offers routes for graduates to remain and look for work. Rules change, so confirm with the [Migration Department](https://www.migracija.lt/en) in your final year — but know the option exists and plan for it early rather than in your last month.

## Look after yourself

Your degree depends on your health more than on any study technique.

- Sleep properly; all-nighters cost more than they gain
- Get outside in daylight, especially in winter
- Eat and move
- Use your university''s psychological support if you are struggling. Being far from family is hard, and asking for help is not failure.

## Stay in touch with us

AfaqWay does not disappear at graduation. If you need advice on internships, staying in Lithuania, or another degree, message us.

## Academic Success Checklist

- [ ] Study habits established and working
- [ ] All deadlines in one calendar
- [ ] Library and academic support used at least once
- [ ] One lecturer I could ask for a reference
- [ ] One society, club or volunteering commitment
- [ ] LinkedIn current
- [ ] Post-graduation options understood
- [ ] Sleep, daylight and exercise treated as part of studying
- [ ] AfaqWay Support saved for whatever comes next', '{"summary":"Finishing your degree well, and what comes after.","source":"xlsx"}'::jsonb, 'student');
end loop;
end $s5$;
