-- Stage 5 chunk 99 · archive steps the content no longer lists · generated by scripts/emit-stage5-chunks.mjs — do not hand-edit.

update public.journey_steps set status = 'archived'
 where stage_id in (
   select id from public.journey_stages
    where country = 'LT' and title = 'Arrival in Lithuania'
 )
   and status <> 'archived'
   and title not in ('Congratulations! Welcome to Lithuania 🎉', 'Accommodation', 'Arrived in Lithuania', 'Lithuanian SIM / eSIM', 'University Enrollment', 'Residence Registration', 'Banking', 'Healthcare', 'Public Transport', 'Financial Setup', 'Find a Job (Optional)', 'Social Integration', 'Academic Success');

notify pgrst, 'reload schema';
